const STORAGE_KEY = 'career-atlas-v1';
const uid = () => Date.now().toString(36) + Math.random().toString(36).slice(2,6);
const today = () => new Date().toISOString().slice(0,10);

function buildDailyPlan(){
  const phases=[
    {start:'2026-08-22',end:'2026-09-30',name:'重新启动与基础建设',goal:'恢复稳定节奏，完成 CV、LinkedIn、GitHub 和作品集结构，并建立首批目标公司',work:{
      0:[['按 Deadline 重排下周任务','Planning','先检查中国秋招、作品提交和面试截止日期；再安排 3 个关键结果。']],
      1:[['推进 Master Portfolio 可见产出','Portfolio','完成 1–2 个可展示页面；优先 Unreal Hero Project 或现有建筑项目转译。']],
      2:[['筛选并投递中国秋招岗位','Applications','只投 Game Environment、场景设计、游戏空间或 Creative；记录截止日期和作品集要求。']],
      3:[['推进 Unreal Hero Environment','Portfolio','围绕 blockout、modular kit、材质、灯光或 walkthrough 完成一个可验证节点。']],
      4:[['完善 CV、LinkedIn 与 GitHub 门面','Planning','统一姓名、职业定位与视觉语言；完善 GitHub 头像、简介、置顶仓库和项目 README，再轻量联系 1 位从业者。']],
      5:[['完成中国秋招申请或作品提交','Applications','优先即将截止的批次；Portfolio V0.5 可以先投，再根据反馈迭代。']],
      6:[['作品集深度工作约 3 小时','Portfolio','只做一个最重要产出，结束前导出页面、截图或短视频并归档。']]
    }},
    {start:'2026-10-01',end:'2026-11-15',name:'作品集 V1 与验证投递',goal:'完成 Unreal Hero Project、Portfolio V1，并通过真实申请反馈校准方向',work:{
      0:[['周复盘：作品、申请与人脉','Planning','核对本周 KPI；为下周选定一个作品集硬产出和 5 个岗位。']],
      1:[['Portfolio V1 页面制作','Portfolio','完成 1–2 个可交付页面，优先讲清问题、过程、个人贡献和结果。']],
      2:[['Unreal Hero Project 制作与 GitHub 归档','Skill','推进 modular kit、材质、灯光或 cinematic；把过程图、职责与工具整理到项目 README，不上传无授权素材。']],
      3:[['筛选并录入 3 个匹配岗位','Applications','聚焦 Spatial / Experiential / 3D；Architecture 只投与现有训练高度匹配的岗位。']],
      4:[['发送 2 条定制 networking 消息','Networking','至少一位 UCLA 校友；记录联系日期和明确的下一步。']],
      5:[['完成 2 个岗位申请','Applications','一个深度定制、一个标准化申请；检查关键词和文件名。']],
      6:[['作品集深度工作 4–6 小时','Portfolio','完成本周页面或 Hero Project milestone；导出并在不同屏幕检查。'],['收集一次外部反馈','Portfolio','请同学、导师或从业者只回答：定位是否清楚、最弱页面是哪一页。']]
    }},
    {start:'2026-11-16',end:'2027-01-10',name:'稳定投递与面试基础',goal:'修正 Portfolio V1、扩大高匹配申请并建立面试故事库',work:{
      0:[['轻量周复盘与休息','Planning','保留恢复时间，只安排下周最重要的 3 件事。']],
      1:[['修正作品集最弱页面','Portfolio','根据反馈只改一个核心问题，避免无止境全盘重做。']],
      2:[['整理 6 个面试故事','Planning','用 Situation–Action–Result 记录协作、冲突、失败、创新与学习。']],
      3:[['清理岗位管线','Applications','关闭失效岗位，跟进已申请岗位，补充 2 个新机会。']],
      4:[['维护 1 位已有联系人','Networking','发送进度更新或节日问候，不索取 referral。']],
      5:[['完成 1 个高匹配申请','Applications','假期保持管线不断，但不追求数量。']],
      6:[['作品集集中修改 3–4 小时','Portfolio','统一字体、图注、页码与项目叙事；导出 Portfolio V1.1。']]
    }},
    {start:'2027-01-11',end:'2027-03-31',name:'招聘旺季与中国线启动',goal:'累计 150–200 个美国申请、80–120 个有效联系人，并启动中国游戏/创意设计线',work:{
      0:[['复盘申请漏斗并规划下周','Planning','查看申请→回复→面试转化率；决定应改岗位定位、材料还是 networking。']],
      1:[['完成 2 个美国岗位申请','Applications','优先新发布 7 天内岗位；至少一个 Spatial / Experiential / 3D。']],
      2:[['Portfolio V2 / GitHub 项目证据','Portfolio','根据岗位缺口补一个证据，并同步更新置顶项目 README、过程图、个人贡献与可运行说明。']],
      3:[['完成 2 个美国岗位申请','Applications','Architecture 岗位需要与现有训练高度匹配，不挤占核心作品时间。']],
      4:[['联系 2 位从业者并跟进 1 人','Networking','一位美国目标公司联系人；一位中国游戏/创意设计联系人。']],
      5:[['完成 1 个高匹配申请并练习面试','Applications','提交后用英文录音回答 Tell me about yourself 和一个项目故事。']],
      6:[['深度工作：作品集或测试题 4–6 小时','Portfolio','有面试/测试时优先交付；没有时推进 Portfolio V2 与中国版作品集。'],['更新中美双轨 Tracker','Planning','比较岗位成长性、作品匹配度、城市与签证，不只看数量。']]
    }},
    {start:'2027-04-01',end:'2027-05-31',name:'面试、测试题与 Offer 管理',goal:'提高面试转化率，完成测试题，并形成可比较的中美 Offer 选项',work:{
      0:[['复盘面试表现与下周安排','Planning','记录每次问题、回答漏洞、后续动作和预计回复时间。']],
      1:[['面试准备或完成 1 个高匹配申请','Applications','有面试时研究团队与面试官；无面试时补充管线。']],
      2:[['作品测试 / Portfolio 定向调整','Portfolio','按目标岗位重排前 6 页，并准备 5 分钟与 15 分钟两个讲述版本。']],
      3:[['跟进申请与 recruiter','Networking','对 7–10 天无回复的高匹配申请发送一次简洁跟进。']],
      4:[['模拟面试 45 分钟','Planning','练习英文项目讲述、行为问题、签证说明与薪资回答，并记录改进点。']],
      5:[['补充 1–2 个精选机会','Applications','避免因进入面试就停止投递，直到书面 Offer 确认。']],
      6:[['测试题 / 面试深度准备 4–6 小时','Portfolio','围绕最近的真实机会工作；没有流程时完善最匹配项目。']]
    }},
    {start:'2027-06-01',end:'2027-06-30',name:'毕业、Offer 决策与入职',goal:'完成 OPT 与入职准备，理性比较中美机会并确定下一步',work:{
      0:[['每周决策复盘','Planning','更新 Offer / 面试状态、截止日期、风险和下周唯一关键动作。']],
      1:[['跟进最终流程与书面材料','Networking','确认面试反馈、Offer 条款或入职文件，所有承诺尽量落实为书面。']],
      2:[['OPT 与入职材料检查','Planning','核对学校国际学生办公室要求、EAD、I-9 与开始日期；以官方信息为准。']],
      3:[['比较岗位长期价值','Planning','评估职责、导师、成长、签证、城市成本、团队稳定性和作品积累。']],
      4:[['维护关键行业关系','Networking','向帮助过你的人发送简短进度更新与感谢。']],
      5:[['处理未完成流程或补充申请','Applications','在正式接受并确认入职前保持合理备选。']],
      6:[['毕业与入职准备','Planning','整理作品、交接文件、搬迁计划和入职前学习清单；保留休息。']]
    }}
  ];
  const kickoff={
    '2026-08-22':[['补齐主简历基础信息','Planning','步骤：填写姓名、电话、邮箱和两段教育经历；统一日期格式。｜完成标准：基础信息无占位符，导出预览完整。',70],['确定首个作品集主项目','Portfolio','步骤：选定与 Spatial / 3D 岗位最相关的一项，收集至少 8 张素材。｜完成标准：Tracker 已建项目，素材文件夹至少 8 张图。',60],['录入首批 3 家目标公司','Applications','步骤：分别找 Spatial、Visualization、Game/Creative 各 1 家。｜完成标准：岗位 Tracker 新增 3 条完整记录。',30]],
    '2026-08-23':[['完成未来一周时间表','Planning','步骤：为未来 6 天各锁定一个两小时以内的求职时段。｜完成标准：日历中已有 6 个明确时间块。',45],['整理求职资料总文件夹','Planning','步骤：集中简历、实习、作品集和证书文件。｜完成标准：核心资料能在两分钟内找到。',45],['检查 5 个近期岗位','Applications','步骤：确认开放状态、截止日期和作品要求。｜完成标准：Tracker 更新 5 条岗位状态。',20]],
    '2026-08-24':[['完成主简历 Education 模块','Planning','步骤：核对学校英文名称、学位、城市和日期。｜完成标准：Education 无占位符，PDF 完整显示。',70],['提取 1 个真实 JD 的关键词','Applications','步骤：标记职责、软件和作品要求各 3 项。｜完成标准：岗位备注写入 9 个关键词。',35],['更新今日 Tracker','Planning','步骤：记录完成内容和明天第一步。｜完成标准：相关记录已保存。',15]],
    '2026-08-25':[['完成 Agence TER 三条英文 bullet','Planning','步骤：每条按 Action + Tool + Result 写作。｜完成标准：至少 3 条，每条不超过两行。',70],['筛选 3 家相关工作室','Applications','步骤：查看项目风格、招聘页和软件要求。｜完成标准：Tracker 新增 3 家并标记匹配点。',35],['检查简历格式','Planning','步骤：导出 PDF，检查对齐、分页和文件名。｜完成标准：没有溢出或占位符。',15]],
    '2026-08-26':[['完成作品集素材筛选','Portfolio','步骤：挑选 1 张主图和 6–10 张过程图。｜完成标准：建立 Final Select 文件夹。',75],['写项目定位与个人贡献','Portfolio','步骤：各写一句 Problem、Role、Contribution。｜完成标准：三句话已录入 Tracker。',30],['保存第 1 页草图','Portfolio','步骤：画出第 1 页图文区域。｜完成标准：保存一张 layout 草图。',15]],
    '2026-08-27':[['完成 Portfolio 第 1 页','Portfolio','步骤：放入标题、主视觉、角色、时间和工具。｜完成标准：导出可发送页面，50% 缩放仍能读懂。',75],['检查 3 个优秀作品集','Portfolio','步骤：每份只记录一个有效版式做法。｜完成标准：得到 3 条可执行改进。',30],['应用一项版式改进','Portfolio','步骤：选择一项立即修改。｜完成标准：保存 before/after。',15]],
    '2026-08-28':[['录入 7 家目标公司','Applications','步骤：补足 Spatial 3 家、Visualization 2 家、Game/Creative 2 家。｜完成标准：Tracker 累计至少 10 家。',60],['分析 1 个高匹配岗位','Applications','步骤：写清要求、已有证据、缺口和截止日期。｜完成标准：备注四项齐全。',45],['安排周六深度工作','Planning','步骤：确定唯一作品集交付物并备齐素材。｜完成标准：明日可直接开始。',15]],
    '2026-08-29':[['完成 Portfolio 第 2 页','Portfolio','步骤：用过程图说明 Problem、Process 和 Contribution。｜完成标准：页面可独立讲清设计过程。',100],['分析第 2 个真实岗位 JD','Applications','步骤：提取 5 个要求并与现有证据匹配。｜完成标准：确定一个补强动作。',50],['整理本周成果','Planning','步骤：归档简历 PDF、作品页和岗位记录。｜完成标准：文件带日期并可打开。',20]],
    '2026-08-30':[['完成一周质量复盘','Planning','步骤：统计产出、申请准备度和卡点。｜完成标准：写出 3 个有效结果和 1 个瓶颈。',45],['确定下周三个交付物','Planning','步骤：选择简历、作品集和市场行动结果。｜完成标准：每项有日期和验收标准。',45],['发送 1 条行业联系','Networking','步骤：向一位校友或设计师发送定制消息。｜完成标准：已发送并设置跟进日期。',20]],
    '2026-08-31':[['提交第 1 个高匹配申请','Applications','步骤：确认开放，定向调整关键词并检查链接后提交。｜完成标准：收到确认并更新 Tracker。',70],['准备第 2 个申请','Applications','步骤：完成岗位匹配表和简历差异标记。｜完成标准：明天只需复核即可提交。',35],['记录投递经验','Planning','步骤：写下最耗时环节和可复用内容。｜完成标准：形成一条流程改进。',15]],
    '2026-09-01':[['完善 Portfolio 第 2 页','Portfolio','步骤：精简文字、统一图注并强化个人贡献。｜完成标准：页面无空话且层级清楚。',70],['提交第 2 个高匹配申请','Applications','步骤：复核岗位、简历和作品链接后提交。｜完成标准：Tracker 状态为已投递。',35],['更新申请统计','Planning','步骤：记录渠道、版本和下一步日期。｜完成标准：两次申请都可追溯。',15]],
    '2026-09-02':[['完成 Unreal Blockout','Skill','步骤：建立主要体块、尺度参照和一个相机视角。｜完成标准：项目可重开，保存 2 张截图。',75],['建立 Unreal 过程记录','Portfolio','步骤：记录目标、当前状态和下一节点。｜完成标准：Portfolio Tracker 已更新。',30],['整理参考图','Skill','步骤：只保留 12 张关键参考并分类。｜完成标准：参考板可直接指导制作。',15]],
    '2026-09-03':[['完成 LinkedIn 基础更新','Planning','步骤：统一标题，写 80–120 词 About，补齐 UCLA 与实习。｜完成标准：核心栏目无空白。',70],['检查 GitHub 公开门面','Planning','步骤：检查简介、置顶仓库、README 和公开文件。｜完成标准：链接可打开且无敏感内容。',35],['统一职业定位','Planning','步骤：对比简历、LinkedIn、GitHub 和 Portfolio 标题。｜完成标准：四处表达一致。',15]],
    '2026-09-04':[['联系 2 位目标行业人士','Networking','步骤：一位 UCLA 校友、一位目标公司设计师，各发定制消息。｜完成标准：两条已发送并记录跟进日期。',45],['筛选 3 个周末可申请岗位','Applications','步骤：确认开放状态、匹配证据和截止日期。｜完成标准：选出优先顺序 1–3。',45],['准备周六作品集任务','Portfolio','步骤：列出所需图文并打开源文件。｜完成标准：明日可直接开始制作。',20]],
    '2026-09-05':[['完成 Portfolio 两页深度制作','Portfolio','步骤：分两个 70 分钟区块完成版式、图注和叙事。｜完成标准：新增或完成 2 页。',140],['导出并检查 Portfolio PDF','Portfolio','步骤：检查字体、边距、清晰度和文件大小。｜完成标准：保存带日期的可发送版本。',25],['提交 1 个精选岗位','Applications','步骤：使用最匹配的材料完成申请。｜完成标准：收到确认并更新 Tracker。',15]],
    '2026-09-06':[['完成数据复盘','Planning','步骤：统计作品页、申请、回复和联系人。｜完成标准：Dashboard 数据已更新。',35],['获得一次作品集反馈','Portfolio','步骤：请一位同学或从业者指出定位和最弱页面。｜完成标准：记录至少 2 条具体反馈。',45],['安排下周 5 个时间块','Planning','步骤：围绕最大瓶颈安排每天不超过两小时。｜完成标准：日历已有 5 个时间块。',20]]
  };
  const out=[],start=new Date('2026-08-22T12:00:00'),end=new Date('2027-06-30T12:00:00');
  for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){
    const iso=d.toISOString().slice(0,10),phase=phases.find(p=>iso>=p.start&&iso<=p.end),day=d.getDay();
    if(!phase)continue;
    const selected=kickoff[iso]||phase.work[day].slice(0,1);
    selected.forEach((x,i)=>out.push({id:`plan-${iso}-${i}`,title:x[0].replace(/4–6 小时/g,'约 3 小时').replace(/3–4 小时/g,'约 3 小时'),category:x[1],date:iso,done:false,opportunity:/申请|秋招|作品集|Portfolio|Hero/i.test(x[0])?'High':'Medium',readiness:'Partial',effort:x[3]||(day===6?180:90),note:`${phase.name}｜${x[2].replace(/4–6 小时/g,'约 3 小时').replace(/3–4 小时/g,'约 3 小时')}`}));
  }
  return out;
}
const initialData = {
  tasks: buildDailyPlan(),
  jobs: [
    {id:'j1',company:'Moment Factory',role:'Junior Multimedia Designer',country:'美国',city:'Los Angeles',direction:'Experiential',status:'准备申请',date:'',contact:'',salary:'$65k–80k',notes:'定制作品集前 6 页'},
    {id:'j2',company:'Gensler',role:'Junior Designer',country:'美国',city:'Los Angeles',direction:'Architecture',status:'准备申请',date:'',contact:'',salary:'',notes:'建筑与可视化匹配岗位'},
    {id:'j3',company:'腾讯游戏',role:'场景设计师',country:'中国',city:'深圳',direction:'Game',status:'关注',date:'',contact:'',salary:'',notes:'2027 春招'}
  ],
  contacts: [
    {id:'c1',name:'Alex Chen',company:'Experiential Studio',role:'Spatial Designer',country:'美国',channel:'LinkedIn',status:'待联系',lastDate:'',next:'发送 coffee chat 邀请',notes:'UCLA 校友示例'},
    {id:'c2',name:'Mia Wang',company:'Game Studio',role:'Environment Artist',country:'中国',channel:'微信',status:'待联系',lastDate:'',next:'询问作品集建议',notes:''}
  ],
  projects: [
    {id:'p1',name:'Unreal Environment Hero Project',type:'Game / Environment',track:'美国/中国',progress:0,deadline:'2026-11-15',next:'确定主题、参考图与首个 modular kit',notes:'核心转型项目'},
    {id:'p2',name:'Agence TER Internship',type:'Landscape / Spatial',track:'美国',progress:0,deadline:'2026-09-30',next:'收集并整理项目素材',notes:'突出专业实践'},
    {id:'p3',name:'AI-assisted Architecture Research',type:'AI / Architecture',track:'美国',progress:0,deadline:'2026-10-20',next:'建立项目叙事大纲',notes:'跨界差异化项目'},
    {id:'p4',name:'UCLA Studio Project',type:'Spatial / Experiential',track:'美国',progress:0,deadline:'2027-02-15',next:'建立每周归档流程',notes:'随课程持续更新'}
  ],
  resumes: [
    {id:'resume-us-spatial',versionName:'US Spatial / Experiential',track:'Spatial / Experience',fullName:'',headline:'Spatial Designer | 3D & Real-time Environments',email:'',phone:'',location:'Los Angeles, CA',linkedin:'',portfolio:'',summary:'',education:'University of California, Los Angeles (UCLA) | Los Angeles, US\nMaster of Science in Architecture and Urban Design | Aug 2026 - Jun 2027 (Expected)\n\nCentral South University | Changsha, China\nBachelor of Architecture | Sept 2021 - Jun 2026',experience:'Agence TER (Shanghai) Co., Ltd. | Shanghai, China\nDesign Intern | Aug 2025 - Dec 2025\n• [Describe your contribution, tools, and measurable result]',projects:'Unreal Environment Hero Project | [City]\nEnvironment / Spatial Designer | [Year]\n• [Describe the spatial narrative, workflow, and result]\n\nAI-assisted Architecture Research | [City]\nDesigner / Researcher | [Year]\n• [Describe the research question and your contribution]',activities:'',awards:'',skills:'• Design: Spatial storytelling, architectural design, visualization\n• 3D & Visualization: Blender, Unreal Engine\n• Visual Tools: Stable Diffusion, [Add Adobe / CAD tools you can demonstrate]',updatedAt:''},
    {id:'resume-us-arch',versionName:'US Architecture / Visualization',track:'Architecture / Visualization',fullName:'',headline:'Architectural Designer | Visualization & Digital Design',email:'',phone:'',location:'Los Angeles, CA',linkedin:'',portfolio:'',summary:'',education:'University of California, Los Angeles (UCLA) | Los Angeles, US\nMaster of Science in Architecture and Urban Design | Aug 2026 - Jun 2027 (Expected)\n\nCentral South University | Changsha, China\nBachelor of Architecture | Sept 2021 - Jun 2026',experience:'Agence TER (Shanghai) Co., Ltd. | Shanghai, China\nDesign Intern | Aug 2025 - Dec 2025\n• [Describe project scope, drawing/modeling contribution, and result]',projects:'Selected Architecture Studio | [City]\nArchitectural Designer | [Year]\n• [Describe the design problem, your role, and final deliverables]\n\nAI-assisted Architecture Research | [City]\nDesigner / Researcher | [Year]\n• [Explain how computation or AI improved the design process]',activities:'',awards:'',skills:'• Design: Architectural design, site analysis, visualization\n• 3D & Visualization: Blender, Unreal Engine, [Add Rhino / CAD tools]\n• Languages: [Add languages and proficiency]',updatedAt:''},
    {id:'resume-cn-game',versionName:'China Game / Creative',track:'Game / Creative',fullName:'',headline:'3D Environment & Spatial Designer',email:'',phone:'',location:'[中国城市 / 可远程]',linkedin:'',portfolio:'',summary:'',education:'加州大学洛杉矶分校（UCLA） | 美国洛杉矶\n建筑与城市设计理学硕士 | 2026.08 - 2027.06（预计）\n\n中南大学 | 中国长沙\n建筑学五年制本科 | 2021.09 - 2026.06',experience:'Agence TER（上海） | 中国上海\n设计实习生 | 2025.08 - 2025.12\n• [用中文描述个人贡献、使用工具和成果]',projects:'Unreal Environment Hero Project | [城市]\n场景 / 空间设计 | [年份]\n• [描述场景主题、模块化流程、材质灯光和最终效果]\n\nAI-assisted Architecture Research | [城市]\n设计 / 研究 | [年份]\n• [描述研究目标和个人贡献]',activities:'',awards:'',skills:'• 3D / 实时：Blender、Unreal Engine\n• 视觉生成：Stable Diffusion\n• 设计：空间叙事、建筑设计、可视化',updatedAt:''}
  ],
  kpi: { portfolioGoal:5, applicationGoal:3, networkingGoal:3, skillGoal:2.5, portfolio:0, applications:0, networking:0, skill:0 },
  settings:{name:'',weekStart:'2026-08-10'}
};
const resumeTitleDefaults={summaryTitle:'PROFILE',educationTitle:'EDUCATION',experienceTitle:'INTERNSHIP EXPERIENCES',projectsTitle:'SELECTED PROJECTS',activitiesTitle:'EXTRACURRICULAR ACTIVITIES',awardsTitle:'HONORS & AWARDS',skillsTitle:'SKILLS'};
const resumeTrackLabels={'resume-us-spatial':'Spatial / Experience','resume-us-arch':'Architecture / Visualization','resume-cn-game':'Game / Creative'};
function legacyResumeSections(r){return [['summary','PROFILE'],['education','EDUCATION'],['experience','INTERNSHIP EXPERIENCES'],['projects','SELECTED PROJECTS'],['activities','EXTRACURRICULAR ACTIVITIES'],['awards','HONORS & AWARDS'],['skills','SKILLS']].map(([key,fallback])=>({id:`section-${key}`,title:r[`${key}Title`]??fallback,content:r[key]||''})).filter(s=>s.content.trim()||['section-education','section-experience','section-projects','section-skills'].includes(s.id))}
function normalizeResumes(resumes){return (resumes||structuredClone(initialData.resumes)).map(r=>{let merged={...resumeTitleDefaults,...r,track:resumeTrackLabels[r.id]||r.track,activities:r.activities||'',awards:r.awards||''};return {...merged,sections:Array.isArray(r.sections)?r.sections.map(s=>({id:s.id||uid(),title:String(s.title||''),content:String(s.content||'')})):legacyResumeSections(merged)}})}
let data = load();
data.resumes=normalizeResumes(data.resumes);
let currentView='dashboard'; let selectedResumeId='resume-us-spatial';
const navItems=[['dashboard','⌂','Dashboard'],['tasks','✓','每日任务'],['resume','▤','简历中心'],['searchhub','⌕','在线搜索'],['jobs','▦','岗位 Tracker'],['network','◎','Networking'],['portfolio','◇','Portfolio'],['timeline','◷','时间线'],['strategy','⇄','职业策略']];
const titles={dashboard:['OVERVIEW','早上好，继续向前。'],tasks:['DAILY RHYTHM','今天要完成什么？'],resume:['RESUME STUDIO','一份经历，多个定向版本'],searchhub:['SEARCH HUB','全球招聘资源导航'],jobs:['OPPORTUNITIES','岗位 Tracker'],network:['RELATIONSHIPS','Networking Tracker'],portfolio:['CRAFT & PROOF','Portfolio 项目'],timeline:['AUG 2026 — JUN 2027','你的求职时间线'],strategy:['CAREER STRATEGY','职业资产与市场策略']};
function load(){try{let saved=JSON.parse(localStorage.getItem(STORAGE_KEY))||{},oldTasks=saved.tasks||[],oldById=new Map(oldTasks.map(t=>[t.id,t])),plans=buildDailyPlan().map(t=>({...t,done:oldById.get(t.id)?.done||false})),custom=oldTasks.filter(t=>!String(t.id).startsWith('plan-'));return {...structuredClone(initialData),...saved,tasks:[...custom,...plans]}}catch{return structuredClone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));render();}
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function init(){document.getElementById('nav').innerHTML=navItems.map(([id,icon,label])=>`<button class="nav-item" data-view="${id}"><i>${icon}</i>${label}</button>`).join('');document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());document.getElementById('nav').onclick=e=>{let b=e.target.closest('[data-view]');if(b){currentView=b.dataset.view;render()}};document.getElementById('quickAdd').onclick=()=>openModal(currentView==='dashboard'?'task':({tasks:'task',jobs:'job',network:'contact',portfolio:'project'}[currentView]||'task'));document.getElementById('updateBtn').onclick=()=>checkForUpdate(true);document.getElementById('resetDemo').title='清零并恢复计划模板';document.getElementById('resetDemo').onclick=()=>{if(confirm('确定清零所有进度？计划模板会保留，但你的打卡、KPI、投递、联系和作品集进度都会归零。')){data=structuredClone(initialData);data.resumes=normalizeResumes(data.resumes);save();toast('进度已清零，计划模板已保留')}};render();setTimeout(()=>checkForUpdate(false),2500)}
async function checkForUpdate(manual=false){if(!window.careerAtlas?.checkUpdate){if(manual)toast('当前版本不支持在线更新');return}let btn=document.getElementById('updateBtn');btn.textContent='检查中…';btn.disabled=true;let result=await window.careerAtlas.checkUpdate();btn.textContent='检查更新';btn.disabled=false;if(!result.ok){if(manual)toast('暂时无法连接更新服务器');return}if(!result.available){if(manual)toast(`已是最新版本 ${result.current}`);return}showUpdateModal(result)}
function showUpdateModal(info){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">UPDATE AVAILABLE</p><h2>发现新版本 ${esc(info.latest)}</h2></div><button class="close" type="button">×</button></div><p class="subtle">当前版本 ${esc(info.current)}。更新会保留你的任务、岗位、联系人和作品集数据。</p><div class="update-notes">${esc(info.notes||'包含功能改进与问题修复。')}</div><div class="modal-actions"><button class="secondary close" type="button">稍后</button><button class="primary" id="installUpdate" ${info.downloadUrl?'':'disabled'}>下载并重启安装</button></div></div></div>`;let root=document.getElementById('modalRoot');root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.innerHTML='');let install=root.querySelector('#installUpdate');install.onclick=async()=>{install.disabled=true;install.textContent='正在下载，请稍候…';try{await window.careerAtlas.installUpdate({downloadUrl:info.downloadUrl,assetName:info.assetName})}catch{install.disabled=false;install.textContent='重试下载';toast('更新下载失败，请稍后重试')}}}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.getElementById('pageEyebrow').textContent=titles[currentView][0];document.getElementById('pageTitle').textContent=titles[currentView][1];document.getElementById('content').innerHTML=({dashboard:dashboardView,tasks:tasksView,resume:resumeView,searchhub:searchHubView,jobs:jobsView,network:networkView,portfolio:portfolioView,timeline:timelineView,strategy:strategyView}[currentView])();bindView();if(currentView==='resume')bindResumeEditor()}
const pct=(v,g)=>Math.min(100,Math.round((v/g)*100));
const careerStages=[
  {id:'foundation',name:'Stage 1 · Restart & Foundation',start:'2026-08-22',end:'2026-09-30',focus:'先恢复稳定行动，再形成可被判断的职业身份；不补欠账，只完成今天。',goals:{portfolio:6,applications:2,networking:2,skill:1.5},weights:{Portfolio:45,Applications:25,Planning:20,Skill:8,Networking:8},mix:[['Portfolio / 定位',45,'每周一个可见产出'],['精选申请',25,'先真实反馈，不做海投'],['材料与系统',20,'CV、LinkedIn、GitHub'],['Networking / Skill',10,'少量高质量推进']]},
  {id:'portfolio',name:'Stage 2 · Portfolio Ready',start:'2026-10-01',end:'2026-11-15',focus:'完成 Portfolio V1 与 Hero Project，并通过真实申请反馈快速迭代。',goals:{portfolio:9,applications:5,networking:3,skill:2.5},weights:{Portfolio:45,Applications:30,Networking:12,Skill:10,Planning:8},mix:[['Portfolio V1',45,'Hero Environment 优先'],['验证投递',30,'申请、测试与反馈'],['Networking',15,'有基础页面后逐步增加'],['Skill gap',10,'只补岗位必需项']]},
  {id:'market',name:'Stage 3 · Market Ready',start:'2026-11-16',end:'2027-03-31',focus:'从 building 转向 selling：投递、连接、面试、反馈、再迭代。',goals:{portfolio:5,applications:8,networking:5,skill:2},weights:{Applications:40,Networking:25,Portfolio:22,Planning:10,Skill:8},mix:[['Applications',40,'高匹配机会优先'],['Networking',25,'校友、从业者与 recruiter'],['Portfolio',25,'按反馈定向修正'],['Interview / Skill',10,'围绕真实机会准备']]},
  {id:'interview',name:'Stage 4 · Interview',start:'2027-04-01',end:'2027-06-30',focus:'优先真实流程、测试题、面试、跟进与 Offer 决策。',goals:{portfolio:3,applications:4,networking:4,skill:1},weights:{Planning:40,Networking:28,Applications:22,Portfolio:18,Skill:5},mix:[['Interview / Tests',40,'最近的真实机会第一'],['Follow-up',25,'推进现有流程'],['Applications',20,'书面 Offer 前保持管线'],['Portfolio',15,'只做岗位定向调整']]}
];
function currentStage(date=today()){if(date<careerStages[0].start)return careerStages[0];return careerStages.find(s=>date>=s.start&&date<=s.end)||careerStages[careerStages.length-1]}
function priorityTasks(rows){let opportunity={High:0,Medium:1,Low:2},readiness={Ready:0,Partial:1,Blocked:2};return [...rows].sort((a,b)=>a.date.localeCompare(b.date)||Number(a.done)-Number(b.done)||(opportunity[a.opportunity||'Medium']-opportunity[b.opportunity||'Medium'])||(readiness[a.readiness||'Partial']-readiness[b.readiness||'Partial'])||Number(a.effort||90)-Number(b.effort||90))}
function stats(){let now=new Date(today()+'T12:00:00'),day=(now.getDay()+6)%7,monday=new Date(now);monday.setDate(now.getDate()-day);let sunday=new Date(monday);sunday.setDate(monday.getDate()+6);let start=monday.toISOString().slice(0,10),end=sunday.toISOString().slice(0,10),week=data.tasks.filter(t=>t.date>=start&&t.date<=end),done=week.filter(t=>t.done).length;return {completion:week.length?pct(done,week.length):0,apps:data.jobs.filter(j=>j.status!=='关注'&&j.status!=='准备申请').length,contacts:data.contacts.filter(c=>c.status!=='待联系').length,portfolio:Math.round(data.projects.reduce((s,p)=>s+Number(p.progress),0)/(data.projects.length||1))}}
function dashboardView(){let s=stats(),k=data.kpi,stage=currentStage(),g=stage.goals,overall=Math.round([pct(k.portfolio,g.portfolio),pct(k.applications,g.applications),pct(k.networking,g.networking),pct(k.skill,g.skill)].reduce((a,b)=>a+b,0)/4),horizon=data.tasks.filter(t=>t.date>=today()&&t.date<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)),daily=priorityTasks(horizon).slice(0,4);return `<div class="stage-banner"><div><span class="tag both">${stage.name}</span><h2>${stage.focus}</h2><p>任务按日期排列；同一天未完成优先，再看机会价值、准备度和预计时间。</p></div><strong>${stage.start.slice(5)} — ${stage.end.slice(5)}</strong></div><div class="grid stats">${statCard('本周完成率',s.completion+'%','✓','从今天重新计算，不补欠账')}${statCard('累计投递',s.apps,'↗','按岗位匹配度管理')}${statCard('有效联系人',s.contacts,'◎','现阶段重质量不重数量')}${statCard('作品集进度',s.portfolio+'%','◇','当前最重要的职业资产')}</div><div class="grid dashboard-grid"><div class="grid"><div class="card"><div class="card-head"><div><h2>阶段自适应 KPI</h2><span class="subtle">恢复期目标较轻，稳定后自动提高</span></div><button class="secondary" data-action="edit-kpi">更新数据</button></div><div class="kpi-wrap"><div class="progress-ring" style="--p:${overall}"><div class="ring-copy"><strong>${overall}%</strong><span>WEEKLY</span></div></div><div class="kpi-list">${kpiRow('Portfolio hours',k.portfolio,g.portfolio,'h')}${kpiRow('Applications',k.applications,g.applications,'')}${kpiRow('Networking',k.networking,g.networking,'')}${kpiRow('Skill hours',k.skill,g.skill,'h')}</div></div></div><div class="card"><div class="card-head"><div><h2>未来 7 天</h2><span class="subtle">按日期显示，每天一个能验收的结果</span></div><button class="secondary" data-action="add-task">＋ 添加</button></div><div class="task-list">${daily.map(taskHtml).join('')||empty('未来 7 天没有任务')}</div></div></div><div class="grid"><div class="card"><div class="card-head"><h2>当前阶段投入</h2><span class="subtle">动态权重</span></div><div class="mini-list">${stage.mix.map(x=>direction(...x)).join('')}</div></div><div class="card readiness-card"><div class="card-head"><h2>9 月 30 日检查点</h2><span class="tag">SEP 30</span></div>${readinessItem('CV V1 + UCLA 信息',resumeCompletion(data.resumes?.[0]||{})>=45)}${readinessItem('LinkedIn / GitHub 可被查看',!!data.resumes?.[0]?.linkedin)}${readinessItem('Portfolio V0.5',s.portfolio>=25)}${readinessItem('首批真实申请已提交',data.jobs.some(j=>!['关注','准备申请'].includes(j.status)))}${readinessItem('Unreal Hero Project 已启动',(data.projects.find(p=>/Unreal/i.test(p.name))?.progress||0)>0)}</div></div></div>`}
function readinessItem(label,done){return `<div class="readiness-item ${done?'done':''}"><span>${done?'✓':'○'}</span><b>${label}</b></div>`}
function statCard(label,val,icon,note){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${val}</div><div class="trend">${note}</div></div>`}
function kpiRow(label,v,g,u){return `<div class="kpi-row"><div class="kpi-meta"><span>${label}</span><b>${v}${u} / ${g}${u}</b></div><div class="bar"><span style="width:${pct(v,g)}%"></span></div></div>`}
function direction(label,p,n){return `<div class="direction-card"><div class="direction-head"><strong>${label}</strong><span>${p}%</span></div><div class="bar"><span style="width:${p}%"></span></div><p class="subtle">${n}</p></div>`}
function taskHtml(t){let parts=String(t.note||'').split('｜').filter(Boolean),date=t.date===today()?'今天':t.date;return `<div class="task ${t.done?'done':''}"><span class="check" data-action="toggle-task" data-id="${t.id}">${t.done?'✓':''}</span><div class="task-copy"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(date)} · ${Number(t.effort||90)} 分钟 · ${esc(t.category)}</div><div class="task-details">${parts.map((x,i)=>`<div class="${i===0?'task-phase':x.startsWith('完成标准')?'task-done-rule':''}">${esc(x)}</div>`).join('')}</div></div><span class="row-actions"><button data-action="edit-task" data-id="${t.id}">✎</button><button data-action="delete-task" data-id="${t.id}">×</button></span></div>`}
function visibleTasks(range='today',category='全部类别'){let start=today(),end=start;if(range==='week'){let d=new Date(start+'T12:00:00');d.setDate(d.getDate()+6);end=d.toISOString().slice(0,10)}else if(range==='all'){start='0000-00-00';end='9999-99-99'}return priorityTasks(data.tasks.filter(t=>t.date>=start&&t.date<=end&&(category==='全部类别'||t.category===category)))}
function tasksView(){let rows=visibleTasks(),stage=currentStage();return `<div class="stage-strip"><b>${stage.name}</b><span>${stage.focus}</span></div><div class="toolbar"><select id="dateFilter"><option value="today" selected>每日任务（今天）</option><option value="week">未来 7 天</option><option value="all">所有任务</option></select><select id="taskFilter"><option>全部类别</option>${['Portfolio','Applications','Networking','Skill','Planning'].map(x=>`<option>${x}</option>`)}</select><button class="primary" data-action="add-task">＋ 添加任务</button></div><div class="card task-order-note"><b>排序规则</b><span>先按日期；同一天未完成在前，然后按机会价值 High → Medium → Low、准备度 Ready → Partial → Blocked、预计时间短的在前。</span></div><div class="card"><div class="card-head"><div><h2 id="taskListTitle">每日任务</h2><span class="subtle" id="taskListHint">今天具体要完成的行动</span></div><span class="tag" id="taskCount">${rows.filter(t=>t.done).length} / ${rows.length} 完成</span></div><div class="task-list" id="allTasks">${rows.map(taskHtml).join('')||empty('今天没有任务，可以点击“添加任务”安排一项具体行动')}</div></div>`}
function resumeCompletion(r){let sections=(r.sections||[]).filter(s=>s.content.trim()),checks=[r.fullName,r.email,r.phone,...sections.slice(0,4).map(s=>s.content)];return Math.round(checks.filter(x=>String(x||'').trim()&&!String(x).includes('[')).length/Math.max(checks.length,7)*100)}
function resumeLine(line,index){let clean=line.trim();if(/^[•-]/.test(clean))return `<p class="pv-bullet">• ${esc(clean.replace(/^[•-]\s*/,''))}</p>`;let parts=clean.split(/\s+\|\s+/),left=parts.shift(),right=parts.join(' | ');return `<div class="pv-row ${index===0?'primary':'secondary'}"><span>${esc(left)}</span>${right?`<span>${esc(right)}</span>`:''}</div>`}
function previewSection(title,content){if(!String(content||'').trim())return'';let groups=String(content).trim().split(/\r?\n\s*\r?\n/);return `<section>${String(title||'').trim()?`<h4>${esc(title)}</h4>`:''}${groups.map(group=>`<div class="pv-group">${group.split(/\r?\n/).filter(Boolean).map((line,i)=>resumeLine(line,i)).join('')}</div>`).join('')}</section>`}
function resumeDensity(r){let sections=(r.sections||[]).filter(s=>s.content.trim()),chars=sections.reduce((n,s)=>n+s.title.length+s.content.length,0),lines=sections.reduce((n,s)=>n+s.content.split(/\r?\n/).length,0),score=chars+lines*28+sections.length*70;if(score<1150)return {mode:'spacious',label:'舒展排版',warning:''};if(score<2300)return {mode:'standard',label:'标准排版',warning:''};if(score<3450)return {mode:'compact',label:'紧凑排版',warning:''};return {mode:'dense',label:'密集排版',warning:score>4700?'内容可能超过一页，建议删减或拆分版本。':'内容较多，已自动缩小字号与间距。'}}
function resumeVersionCard(x,r){return `<div class="resume-version ${x.id===r.id?'active':''}"><button class="resume-version-main" data-action="select-resume" data-id="${x.id}"><span class="tag">${esc(x.track||'Custom')}</span><strong>${esc(x.versionName)}</strong><div class="bar"><span style="width:${resumeCompletion(x)}%"></span></div><small>${resumeCompletion(x)}% 完成</small></button><div class="resume-version-actions"><button data-action="resume-version-rename" data-id="${x.id}" title="改名">改名</button><button data-action="resume-version-copy" data-id="${x.id}" title="复制">复制</button><button data-action="resume-version-delete" data-id="${x.id}" title="删除">删除</button></div></div>`}
function resumeView(){let resumes=data.resumes||initialData.resumes,r=resumes.find(x=>x.id===selectedResumeId)||resumes[0],density=resumeDensity(r);selectedResumeId=r.id;return `<div class="resume-layout"><aside class="grid resume-versions"><button class="primary resume-new-version" data-action="resume-version-add">＋ 新建简历版本</button>${resumes.map(x=>resumeVersionCard(x,r)).join('')}<div class="card resume-tip"><h3>版本与模块都可自定义</h3><p>可以新建、复制、改名或删除简历版本。右侧直接使用 PDF 打印模板，预览与导出保持一致。</p></div></aside><div class="card resume-editor"><div class="card-head"><div><h2>${esc(r.versionName)}</h2><span class="subtle">所有修改都会自动保存在本机</span></div><div class="resume-head-actions"><span class="tag" id="resumeCompletion">${resumeCompletion(r)}% 完成</span><button class="secondary" type="button" data-action="resume-add-section">＋ 新增模块</button></div></div><form id="resumeForm" class="resume-form">${resumeField('fullName','姓名',r.fullName,'text')}${resumeField('headline','职业标题（仅用于版本管理，不显示在版面）',r.headline,'text','full')}${resumeField('email','Email',r.email,'email')}${resumeField('phone','电话',r.phone,'text')}${resumeField('location','城市',r.location,'text')}${resumeField('linkedin','LinkedIn',r.linkedin,'url')}${resumeField('portfolio','Portfolio URL',r.portfolio,'url','full')}<div class="resume-section-list">${(r.sections||[]).map((s,i)=>resumeSectionEditor(s,i,r.sections.length)).join('')}</div></form></div><div class="resume-preview-col"><div class="card-head resume-export-head"><div><h2>打印预览</h2><span class="subtle">与最终 PDF 共用同一份 Letter 模板</span></div><span class="layout-badge ${density.mode}" id="resumeDensity">${density.label}</span></div><div id="resumeWarning">${density.warning?`<div class="resume-warning">${density.warning}</div>`:''}</div><div id="resumePreview" class="resume-print-preview"><iframe id="resumePreviewFrame" title="简历打印预览"></iframe></div><div class="resume-export"><button class="secondary" data-action="resume-word">导出 Word</button><button class="primary" data-action="resume-pdf">导出 PDF</button></div></div></div>`}
function resumeSectionEditor(section,index,total){return `<div class="field full resume-section-editor" data-section-id="${esc(section.id)}"><div class="resume-section-toolbar"><label>模块 ${index+1}</label><div><button type="button" data-action="resume-section-up" data-id="${esc(section.id)}" ${index===0?'disabled':''}>↑</button><button type="button" data-action="resume-section-down" data-id="${esc(section.id)}" ${index===total-1?'disabled':''}>↓</button><button type="button" class="remove-section" data-action="resume-section-delete" data-id="${esc(section.id)}" title="删除模块" aria-label="删除模块">×</button></div></div><input class="section-title-input" data-section-field="title" value="${esc(section.title||'')}" placeholder="例如 EDUCATION / EXHIBITIONS"><textarea data-section-field="content" placeholder="输入这一模块的内容">${esc(section.content||'')}</textarea></div>`}
function resumeField(name,label,value,type,extra=''){let control=type==='textarea'?`<textarea name="${name}">${esc(value||'')}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value||'')}">`;return `<div class="field ${extra}"><label>${label}</label>${control}</div>`}
function currentResume(){return (data.resumes||[]).find(x=>x.id===selectedResumeId)}
let previewRequest=0;
function fitResumePreview(){let box=document.getElementById('resumePreview'),frame=document.getElementById('resumePreviewFrame');if(!box||!frame)return;let scale=Math.min(1,box.clientWidth/816),contentHeight=1056;try{contentHeight=Math.max(1056,frame.contentDocument?.documentElement?.scrollHeight||1056)}catch{}frame.style.height=`${contentHeight}px`;frame.style.transform=`scale(${scale})`;box.style.height=`${contentHeight*scale}px`}
async function refreshResumePreview(r=currentResume()){let frame=document.getElementById('resumePreviewFrame');if(!frame||!r)return;let request=++previewRequest;try{let html=await window.careerAtlas.renderResumePreview(r);if(request===previewRequest&&document.getElementById('resumePreviewFrame')){frame.onload=fitResumePreview;frame.srcdoc=html;fitResumePreview()}}catch{frame.srcdoc='<p style="font-family:sans-serif;padding:20px">预览暂时无法加载，请重新进入简历中心。</p>'}}
function bindResumeEditor(){let form=document.getElementById('resumeForm');if(!form)return;refreshResumePreview();let box=document.getElementById('resumePreview');if(box)new ResizeObserver(fitResumePreview).observe(box);form.oninput=e=>{let r=currentResume(),sectionBox=e.target.closest('[data-section-id]');if(sectionBox&&e.target.dataset.sectionField){let s=r.sections.find(x=>x.id===sectionBox.dataset.sectionId);if(s)s[e.target.dataset.sectionField]=String(e.target.value)}else if(e.target.name)r[e.target.name]=String(e.target.value);r.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));let density=resumeDensity(r);refreshResumePreview(r);document.getElementById('resumeCompletion').textContent=`${resumeCompletion(r)}% 完成`;let badge=document.getElementById('resumeDensity');badge.className=`layout-badge ${density.mode}`;badge.textContent=density.label;document.getElementById('resumeWarning').innerHTML=density.warning?`<div class="resume-warning">${density.warning}</div>`:''}}
function addResumeSection(){let r=currentResume();r.sections.push({id:uid(),title:'NEW SECTION',content:''});save();toast('已新增简历模块')}
function moveResumeSection(id,delta){let r=currentResume(),i=r.sections.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=r.sections.length)return;[r.sections[i],r.sections[j]]=[r.sections[j],r.sections[i]];save()}
function deleteResumeSection(id){let r=currentResume(),s=r.sections.find(x=>x.id===id);if(s&&confirm(`确定删除“${s.title||'未命名模块'}”及其中内容？`)){r.sections=r.sections.filter(x=>x.id!==id);save();toast('模块已删除')}}
function addResumeVersion(){let name=prompt('新简历版本名称：','New Targeted Resume');if(!name?.trim())return;let base=currentResume()||data.resumes[0],copy=structuredClone(base);copy.id=`resume-${uid()}`;copy.versionName=name.trim();copy.track='Custom';copy.updatedAt=new Date().toISOString();data.resumes.push(copy);selectedResumeId=copy.id;save();toast('已新建简历版本')}
function renameResumeVersion(id){let r=data.resumes.find(x=>x.id===id),name=r&&prompt('修改简历版本名称：',r.versionName);if(name?.trim()){r.versionName=name.trim();let track=prompt('方向标签（可选）：',r.track||'Custom');if(track!==null)r.track=track.trim()||'Custom';save();toast('版本名称已更新')}}
function copyResumeVersion(id){let source=data.resumes.find(x=>x.id===id);if(!source)return;let copy=structuredClone(source);copy.id=`resume-${uid()}`;copy.versionName=`${source.versionName} Copy`;copy.updatedAt=new Date().toISOString();data.resumes.push(copy);selectedResumeId=copy.id;save();toast('已复制简历版本')}
function deleteResumeVersion(id){if(data.resumes.length<=1){toast('至少保留一个简历版本');return}let r=data.resumes.find(x=>x.id===id);if(r&&confirm(`确定删除简历版本“${r.versionName}”？其中内容也会删除。`)){data.resumes=data.resumes.filter(x=>x.id!==id);if(selectedResumeId===id)selectedResumeId=data.resumes[0].id;save();toast('简历版本已删除')}}
const columns={jobs:[['company','公司'],['role','岗位'],['place','国家 / 城市'],['direction','方向'],['status','状态'],['date','投递日期'],['contact','联系人'],['salary','薪资']],contacts:[['name','姓名'],['company','公司'],['role','职位'],['country','国家'],['channel','渠道'],['status','状态'],['lastDate','最近联系'],['next','下一步']]};
const searchSourceGroups=[
  {title:'综合招聘',note:'覆盖面广，适合建立基础岗位管线',sources:[
    ['linkedin-jobs','in','LinkedIn Jobs','岗位、公司和招聘动态；适合结合发布时间与经验等级筛选。','global'],
    ['indeed','I','Indeed','覆盖广泛的美国职位，适合补充公司官网之外的机会。','global'],
    ['glassdoor','G','Glassdoor','岗位搜索结合公司评价与薪资信息，适合申请前研究。','global'],
    ['builtin','B','Built In','科技、创意与数字产品岗位较集中，适合跨界设计职位。','global'],
    ['wellfound','W','Wellfound','创业公司与小型团队岗位，适合寻找职责更综合的机会。','global']
  ]},
  {title:'校园与关系网络',note:'学校资源和行业联系人搜索',sources:[
    ['linkedin-people','in','LinkedIn People','查找校友、目标公司从业者、recruiter 与 hiring manager。','network'],
    ['handshake','H','UCLA Handshake','学生岗位、校园招聘活动与雇主信息。','campus'],
    ['12twenty','12','UCLA 12Twenty','UCLA 职业系统中的岗位、活动和校友资源。','campus']
  ]},
  {title:'设计与建筑',note:'更接近作品集导向的专业岗位',sources:[
    ['archinect','A','Archinect Jobs','建筑、城市、景观、可视化与设计事务所岗位。','design'],
    ['aia','AIA','AIA Career Center','美国建筑行业职业平台，可补充事务所职位。','design'],
    ['dezeen','D','Dezeen Jobs','国际建筑、室内、产品与创意设计岗位。','design'],
    ['coroflot','C','Coroflot Design Jobs','工业、视觉、体验、空间与数字设计岗位。','design']
  ]},
  {title:'游戏与创意技术',note:'场景、3D、实时引擎与游戏行业机会',sources:[
    ['hitmarker','H','Hitmarker','游戏、电竞与互动娱乐岗位，适合 Environment / 3D 搜索。','game'],
    ['artstation','Art','ArtStation Jobs','游戏美术、概念、场景与技术美术职位。','game']
  ]},
  {title:'中国招聘与职场网络',note:'综合招聘、校招与行业关系并行使用',sources:[
    ['zhipin','BOSS','BOSS直聘','职位数量大、沟通直接；注意核实公司与岗位真实性。','china'],
    ['liepin','猎','猎聘','中高端与专业岗位较多，适合公司和岗位交叉搜索。','china'],
    ['zhaopin','智','智联招聘','综合招聘与校园招聘入口。','china'],
    ['51job','51','前程无忧','综合岗位和企业招聘信息，可作为覆盖补充。','china'],
    ['lagou','拉','拉勾','互联网、游戏、产品与设计岗位。','china'],
    ['nowcoder','牛','牛客校招','校招、笔试经验与企业招聘日程。','china'],
    ['maimai','脉','脉脉','公司信息、行业讨论与职场联系人发现。','network']
  ]}
];
function searchSourceCard(s){return `<div class="card source-card"><span class="source-logo ${s[4]}">${s[1]}</span><div><h3>${s[2]}</h3><p>${s[3]}</p></div><button class="primary" data-action="open-search" data-platform="${s[0]}">打开官网 ↗</button></div>`}
function searchHubView(){return `<div class="card search-hero"><div><span class="tag us">官方渠道导航</span><h2>招聘与行业资源中心</h2><p class="subtle">输入关键词和城市，再打开需要的平台。登录与搜索发生在各平台官网，Career Atlas 不读取账号，也不保存密码。</p></div><div class="search-form"><div class="field"><label>岗位 / 技能 / 公司关键词</label><input id="onlineQuery" value="Spatial Designer" placeholder="例如 Spatial Designer / Unreal / 场景设计"></div><div class="field"><label>城市（支持的平台会自动带入）</label><input id="onlineLocation" value="Los Angeles" placeholder="例如 Los Angeles / 上海"></div></div></div>${searchSourceGroups.map(g=>`<section class="search-section"><div class="search-section-head"><div><h2>${g.title}</h2><p>${g.note}</p></div><span>${g.sources.length} 个渠道</span></div><div class="grid search-grid">${g.sources.map(searchSourceCard).join('')}</div></section>`).join('')}<div class="card search-note"><b>使用建议</b><span>综合平台负责发现机会，垂直平台负责提高匹配度，公司官网负责最终核实。不要在任何平台向陌生人提供验证码或付款。</span></div><div class="card capture-card"><div><h2>找到结果后快速保存</h2><p class="subtle">把官网留在浏览器中，回到这里记录关键内容，避免重复搜索。</p></div><div><button class="secondary" data-action="add-contact">＋ 保存联系人</button> <button class="primary" data-action="add-job">＋ 保存岗位</button></div></div>`}
function openOnlineSearch(platform){let q=encodeURIComponent(document.getElementById('onlineQuery')?.value.trim()||''),loc=encodeURIComponent(document.getElementById('onlineLocation')?.value.trim()||'');let urls={
  'linkedin-jobs':`https://www.linkedin.com/jobs/search/?keywords=${q}&location=${loc}`,
  'linkedin-people':`https://www.linkedin.com/search/results/people/?keywords=${q}`,
  'indeed':`https://www.indeed.com/jobs?q=${q}&l=${loc}`,
  'glassdoor':`https://www.glassdoor.com/Job/jobs.htm?sc.keyword=${q}&locKeyword=${loc}`,
  'builtin':`https://builtin.com/jobs?search=${q}`,
  'wellfound':'https://wellfound.com/jobs',
  'handshake':`https://app.joinhandshake.com/stu/postings?query=${q}`,
  '12twenty':'https://ucla.12twenty.com/',
  'archinect':'https://archinect.com/jobs',
  'aia':'https://careercenter.aia.org/jobs/',
  'dezeen':'https://www.dezeenjobs.com/',
  'coroflot':'https://www.coroflot.com/design-jobs',
  'hitmarker':`https://hitmarker.net/jobs?search=${q}`,
  'artstation':'https://www.artstation.com/jobs',
  'zhipin':`https://www.zhipin.com/web/geek/job?query=${q}`,
  'liepin':`https://www.liepin.com/zhaopin/?key=${q}`,
  'zhaopin':`https://sou.zhaopin.com/?kw=${q}`,
  '51job':`https://we.51job.com/pc/search?keyword=${q}`,
  'lagou':`https://www.lagou.com/wn/jobs?kd=${q}`,
  'nowcoder':'https://www.nowcoder.com/jobs/school',
  'maimai':'https://maimai.cn/'
};let url=urls[platform];if(!url)return toast('这个渠道暂时不可用');if(window.careerAtlas)window.careerAtlas.openExternal(url).catch(()=>toast('无法打开网页，请检查默认浏览器'));else window.open(url,'_blank')}
function jobsView(){return trackerView('jobs','搜索公司或岗位…','添加岗位','job')}
function networkView(){return trackerView('contacts','搜索姓名或公司…','添加联系人','contact')}
function trackerView(type,placeholder,addLabel,entity){let rows=data[type];return `<div class="toolbar"><input id="search" placeholder="${placeholder}"><select id="trackFilter"><option value="">全部</option>${type==='jobs'?['美国','中国'].map(x=>`<option>${x}</option>`).join(''):['待联系','已联系','保持联系'].map(x=>`<option>${x}</option>`).join('')}</select><button class="secondary" data-action="export" data-type="${type}">⇩ 导出 CSV</button><button class="primary" data-action="add-${entity}">＋ ${addLabel}</button></div><div class="card table-card"><table><thead><tr>${columns[type].map(c=>`<th>${c[1]}</th>`).join('')}<th></th></tr></thead><tbody id="trackerBody">${trackerRows(type,rows)}</tbody></table></div>`}
function trackerRows(type,rows){if(!rows.length)return `<tr><td colspan="9">${empty('还没有记录')}</td></tr>`;return rows.map(r=>`<tr>${columns[type].map(([key])=>{let value=key==='place'?`${r.country} · ${r.city}`:r[key];return `<td>${key==='status'?`<span class="status ${esc(value)}">${esc(value)}</span>`:esc(value||'—')}</td>`}).join('')}<td class="row-actions"><button data-action="edit-${type==='jobs'?'job':'contact'}" data-id="${r.id}">✎</button><button data-action="delete-${type==='jobs'?'job':'contact'}" data-id="${r.id}">×</button></td></tr>`).join('')}
function portfolioView(){return `<div class="toolbar"><span class="subtle">把建筑训练转化为空间叙事、实时 3D 与视觉设计能力。</span><button class="secondary" data-action="export" data-type="projects">⇩ 导出 CSV</button><button class="primary" data-action="add-project">＋ 添加项目</button></div><div class="grid portfolio-grid">${data.projects.map(p=>`<div class="card project-card"><div class="project-top"><span class="tag ${p.track==='美国'?'us':p.track==='中国'?'cn':'both'}">${esc(p.track)}</span><span class="row-actions"><button data-action="edit-project" data-id="${p.id}">✎</button><button data-action="delete-project" data-id="${p.id}">×</button></span></div><h3>${esc(p.name)}</h3><span class="subtle">${esc(p.type)} · ${esc(p.deadline)}</span><p>下一步：${esc(p.next)}</p><div class="project-progress"><span>Progress</span><b>${p.progress}%</b></div><div class="bar"><span style="width:${p.progress}%"></span></div></div>`).join('')||empty('还没有作品集项目')}</div>`}
function timelineView(){let milestones=[['2026.08.22 — 09.30','Stage 1 · Restart & Foundation',['前 7 天恢复节奏：每天只做一个 30–90 分钟核心任务','CV、LinkedIn、GitHub 与 Portfolio V0.5 建立基础','建立目标公司清单并完成第一批真实申请']],['2026.10.01 — 11.15','Stage 2 · Portfolio Ready',['Hero Environment 推进至 60–100%','核心仓库 README 讲清问题、过程、贡献、工具与结果','Portfolio V1 可支持定向申请']],['2026.11.16 — 2027.03','Stage 3 · Market Ready',['Applications + Networking 稳定加速','每月维护 GitHub 置顶项目和个人主页一致性','Apply → Interview → Improve → Apply']],['2027.04 — 05','Stage 4 · Interview',['测试题、面试与 follow-up 优先','用 GitHub / Portfolio 提供可验证的项目证据','比较职责、成长、签证、团队与城市成本']],['2027.06','Offer 决策与入职',['综合比较岗位内容、成长、团队、地点、签证与作品积累','确认 OPT、岗位相关性及入职材料']]];let stage=currentStage();return `<div class="card timeline">${milestones.map((m,i)=>`<div class="milestone ${careerStages[i]?.id===stage.id?'active':''}"><span class="tag">${m[0]}</span><h3 style="margin-top:10px">${m[1]}</h3><ul>${m[2].map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div>`}
function strategyView(){let stage=currentStage();return `<div class="stage-banner"><div><span class="tag both">${stage.name}</span><h2>${stage.focus}</h2><p>职业结果由定位、作品证据、市场行动、关系网络和公开专业形象共同决定。</p></div></div><div class="grid strategy-grid"><div class="card strategy-panel us-panel"><span class="tag us">职业定位与市场组合</span><h2>形成统一但不单一的职业身份</h2><p class="subtle">用 Architecture-trained Spatial / Environment Designer 串联空间、3D、实时与视觉化能力。</p><ul><li>核心岗位：Spatial / Experiential / Real-time / Visualization</li><li>Architecture + Visualization 保持教育与工作授权叙事连续</li><li>Game Environment / Worldbuilding 作为作品驱动的拓展方向</li><li>按真实截止日期、匹配度、成长空间、地点与签证风险排序</li></ul></div><div class="card strategy-panel cn-panel"><span class="tag cn">作品与市场反馈</span><h2>用可判断的作品进入真实市场</h2><p class="subtle">不等待“完美作品集”，先让材料可读，再根据岗位、测试和面试反馈迭代。</p><ul><li>每个项目清楚说明问题、个人角色、过程、工具与结果</li><li>维护针对不同岗位的简历版本和作品顺序</li><li>记录申请限制、作品要求、截止日期和反馈</li><li>每月检查申请→回复→面试转化率，定位真正瓶颈</li></ul></div><div class="card strategy-panel github-panel"><span class="tag">PUBLIC PROOF</span><h2>把 GitHub 建成专业证据库</h2><p class="subtle">目标不是刷提交次数，而是让招聘方快速理解你如何工作、如何组织复杂项目。</p><ul><li>主页简介只保留职业定位、核心工具、Portfolio 与 LinkedIn</li><li>置顶 3–4 个最相关仓库：Career Atlas、AI/设计研究、技术或实时项目</li><li>每个 README 包含项目目的、个人贡献、流程图/截图、技术栈、运行方法和结果</li><li>不上传 API Key、个人简历数据、未授权公司文件或课程受限材料</li><li>每月一次整理即可，避免 GitHub 挤占作品集和申请时间</li></ul></div><div class="card strategy-panel network-panel"><span class="tag">RELATIONSHIPS & SIGNAL</span><h2>让材料、表达和关系互相增强</h2><p class="subtle">LinkedIn、GitHub、Portfolio、简历和面试叙事应使用一致的职业语言。</p><ul><li>Networking 以校友、目标团队从业者和真实反馈为主</li><li>为 30 秒、5 分钟、15 分钟准备同一套项目叙事</li><li>保留健康、课程和深度创作时间，避免数量型焦虑</li><li>书面 Offer 前保持合理申请管线，并定期备份数据</li></ul></div></div><div class="card priority-logic"><h2>动态排序模型</h2><div class="logic-flow"><span>1 · Deadline</span><b>→</b><span>2 · Readiness</span><b>→</b><span>3 · Opportunity Value</span><b>→</b><span>4 · Career Fit</span><b>→</b><span>5 · Effort</span></div></div>`}
function empty(s){return `<div class="empty">${s}</div>`}
function bindView(){document.getElementById('content').onclick=async e=>{let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action,id=b.dataset.id;if(a==='toggle-task'){let t=data.tasks.find(x=>x.id===id);t.done=!t.done;save()}else if(a==='open-search')openOnlineSearch(b.dataset.platform);else if(a==='select-resume'){selectedResumeId=id;render()}else if(a==='resume-version-add')addResumeVersion();else if(a==='resume-version-rename')renameResumeVersion(id);else if(a==='resume-version-copy')copyResumeVersion(id);else if(a==='resume-version-delete')deleteResumeVersion(id);else if(a==='resume-add-section')addResumeSection();else if(a==='resume-section-up')moveResumeSection(id,-1);else if(a==='resume-section-down')moveResumeSection(id,1);else if(a==='resume-section-delete')deleteResumeSection(id);else if(a==='resume-word'){let r=await window.careerAtlas.exportResumeWord(currentResume());if(!r.canceled)toast('Word 简历已导出')}else if(a==='resume-pdf'){let r=await window.careerAtlas.exportResumePdf(currentResume());if(!r.canceled)toast('PDF 简历已导出')}else if(a.startsWith('add-'))openModal(a.slice(4));else if(a.startsWith('edit-'))openModal(a.slice(5),id);else if(a.startsWith('delete-'))remove(a.slice(7),id);else if(a==='edit-kpi')openModal('kpi');else if(a==='export')exportCsv(b.dataset.type)};let search=document.getElementById('search'),filter=document.getElementById('trackFilter');if(search){let run=()=>{let type=currentView==='jobs'?'jobs':'contacts',q=search.value.toLowerCase(),f=filter.value;let rows=data[type].filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)&&(type==='jobs'?(!f||r.country===f):(!f||r.status===f)));document.getElementById('trackerBody').innerHTML=trackerRows(type,rows)};search.oninput=run;filter.onchange=run}let tf=document.getElementById('taskFilter'),df=document.getElementById('dateFilter');if(tf&&df){let labels={today:['每日任务','今天具体要完成的行动'],week:['未来 7 天','查看接下来一周的具体安排'],all:['所有任务','查看完整求职计划']},run=()=>{let rows=visibleTasks(df.value,tf.value),copy=labels[df.value];document.getElementById('allTasks').innerHTML=rows.map(taskHtml).join('')||empty('这个筛选范围还没有任务');document.getElementById('taskCount').textContent=`${rows.filter(t=>t.done).length} / ${rows.length} 完成`;document.getElementById('taskListTitle').textContent=copy[0];document.getElementById('taskListHint').textContent=copy[1]};tf.onchange=run;df.onchange=run}}
function remove(type,id){let map={task:'tasks',job:'jobs',contact:'contacts',project:'projects'},key=map[type];if(confirm('确定删除这条记录？')){data[key]=data[key].filter(x=>x.id!==id);save();toast('已删除')}}
const forms={
 task:{title:'任务',key:'tasks',fields:[['title','任务名称','text'],['category','类别','select',['Portfolio','Applications','Networking','Skill','Planning']],['date','截止 / 执行日期','date'],['opportunity','机会价值','select',['High','Medium','Low']],['readiness','准备度','select',['Ready','Partial','Blocked']],['effort','预计分钟','number'],['note','说明','textarea']]},
 job:{title:'岗位',key:'jobs',fields:[['company','公司','text'],['role','岗位','text'],['country','国家','select',['美国','中国']],['city','城市','text'],['direction','方向','select',['Experiential','Spatial / 3D','Game','Architecture','Visualization','AI / Creative']],['status','状态','select',['关注','准备申请','已申请','面试中','Offer','拒绝']],['date','投递日期','date'],['contact','联系人','text'],['salary','薪资','text'],['notes','备注','textarea']]},
 contact:{title:'联系人',key:'contacts',fields:[['name','姓名','text'],['company','公司','text'],['role','职位','text'],['country','国家','select',['美国','中国']],['channel','渠道','select',['LinkedIn','Email','微信','校友活动','其他']],['status','状态','select',['待联系','已联系','保持联系']],['lastDate','最近联系','date'],['next','下一步','text'],['notes','备注','textarea']]},
 project:{title:'作品集项目',key:'projects',fields:[['name','项目名称','text'],['type','类型 / 方向','text'],['track','轨道','select',['美国','中国','美国/中国']],['progress','进度 %','number'],['deadline','目标日期','date'],['next','下一步行动','text'],['notes','备注','textarea']]}
};
function openModal(type,id){if(type==='kpi')return kpiModal();let f=forms[type]||forms.task,item=id?data[f.key].find(x=>x.id===id):{};document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="editForm"><div class="modal-head"><div><p class="eyebrow">${id?'EDIT':'NEW'}</p><h2>${id?'编辑':'添加'}${f.title}</h2></div><button class="close" type="button">×</button></div><div class="form-grid">${f.fields.map(([key,label,input,opts])=>fieldHtml(key,label,input,opts,item[key])).join('')}</div><div class="modal-actions"><button class="secondary close" type="button">取消</button><button class="primary" type="submit">保存</button></div></form></div>`;wireModal(form=>{let obj={...item,id:item.id||uid()};f.fields.forEach(([key,,input])=>obj[key]=input==='number'?Number(form.elements[key].value):form.elements[key].value);if(!id&&type==='task')obj.done=false;if(id)data[f.key]=data[f.key].map(x=>x.id===id?obj:x);else data[f.key].unshift(obj);save();toast('已保存')})}
function fieldHtml(key,label,type,opts,val=''){let full=type==='textarea'?' full':'';let control=type==='select'?`<select name="${key}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${key}">${esc(val)}</textarea>`:`<input name="${key}" type="${type}" value="${esc(val)}" ${key==='progress'?'min="0" max="100"':''}>`;return `<div class="field${full}"><label>${label}</label>${control}</div>`}
function kpiModal(){let k=data.kpi;document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="editForm"><div class="modal-head"><div><p class="eyebrow">WEEKLY CHECK-IN</p><h2>更新本周 KPI</h2></div><button class="close" type="button">×</button></div><div class="form-grid">${[['portfolio','Portfolio hours'],['applications','Applications'],['networking','Networking'],['skill','Skill hours']].map(([key,l])=>fieldHtml(key,l,'number',null,k[key])).join('')}</div><div class="modal-actions"><button class="secondary close" type="button">取消</button><button class="primary">保存</button></div></form></div>`;wireModal(form=>{['portfolio','applications','networking','skill'].forEach(x=>data.kpi[x]=Number(form.elements[x].value));save();toast('本周进度已更新')})}
function wireModal(onSubmit){let root=document.getElementById('modalRoot');root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.innerHTML='');root.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))root.innerHTML=''};root.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(e.target);root.innerHTML=''}}
function exportCsv(type){let rows=data[type],cols=type==='jobs'?['company','role','country','city','direction','status','date','contact','salary','notes']:type==='contacts'?['name','company','role','country','channel','status','lastDate','next','notes']:['name','type','track','progress','deadline','next','notes'];let csv=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replace(/"/g,'""')}"`).join(','))].join('\r\n');let names={jobs:'Career-Atlas-Jobs.csv',contacts:'Career-Atlas-Networking.csv',projects:'Career-Atlas-Portfolio.csv'};if(window.careerAtlas)window.careerAtlas.exportCsv({filename:names[type],content:csv}).then(r=>!r.canceled&&toast('CSV 已导出'));else{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download=names[type];a.click();toast('CSV 已导出')}}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
