const STORAGE_KEY = 'career-atlas-v1';
const uid = () => Date.now().toString(36) + Math.random().toString(36).slice(2,6);
const today = () => new Date().toISOString().slice(0,10);

function buildDailyPlan(){
  const phases=[
    {start:'2026-08-15',end:'2026-09-30',name:'定位与基础建设',goal:'完成 CV、LinkedIn、作品集结构，并建立首批 30 家目标公司',work:{
      0:[['按 Deadline 重排下周任务','Planning','先检查中国秋招、作品提交和面试截止日期；再安排 3 个关键结果。']],
      1:[['推进 Master Portfolio 可见产出','Portfolio','完成 1–2 个可展示页面；优先 Unreal Hero Project 或现有建筑项目转译。']],
      2:[['筛选并投递中国秋招岗位','Applications','只投 Game Environment、场景设计、游戏空间或 Creative；记录截止日期和作品集要求。']],
      3:[['推进 Unreal Hero Environment','Portfolio','围绕 blockout、modular kit、材质、灯光或 walkthrough 完成一个可验证节点。']],
      4:[['完善 CV / LinkedIn 并轻量连接','Planning','先补齐职业定位与材料；Networking 只联系 1 位 UCLA 校友或目标行业从业者。']],
      5:[['完成中国秋招申请或作品提交','Applications','优先即将截止的批次；Portfolio V0.5 可以先投，再根据反馈迭代。']],
      6:[['作品集深度工作约 3 小时','Portfolio','只做一个最重要产出，结束前导出页面、截图或短视频并归档。']]
    }},
    {start:'2026-10-01',end:'2026-12-15',name:'作品集 V1 与稳定投递',goal:'完成 Unreal Hero Project、Portfolio V1、100 家目标公司并形成稳定投递节奏',work:{
      0:[['周复盘：作品、申请与人脉','Planning','核对本周 KPI；为下周选定一个作品集硬产出和 5 个岗位。']],
      1:[['Portfolio V1 页面制作','Portfolio','完成 1–2 个可交付页面，优先讲清问题、过程、个人贡献和结果。']],
      2:[['Unreal Hero Project 制作','Skill','按 modular kit → materials → lighting → cinematic 的顺序推进并截图记录。']],
      3:[['筛选并录入 3 个匹配岗位','Applications','主攻 Spatial / Experiential / 3D；Architecture 只投高匹配留美保底岗位。']],
      4:[['发送 2 条定制 networking 消息','Networking','至少一位 UCLA 校友；记录联系日期和明确的下一步。']],
      5:[['完成 2 个岗位申请','Applications','一个深度定制、一个标准化申请；检查关键词和文件名。']],
      6:[['作品集深度工作 4–6 小时','Portfolio','完成本周页面或 Hero Project milestone；导出并在不同屏幕检查。'],['收集一次外部反馈','Portfolio','请同学、导师或从业者只回答：定位是否清楚、最弱页面是哪一页。']]
    }},
    {start:'2026-12-16',end:'2027-01-10',name:'冬季整理与面试基础',goal:'修正 Portfolio V1、整理申请材料并建立面试故事库',work:{
      0:[['轻量周复盘与休息','Planning','保留恢复时间，只安排下周最重要的 3 件事。']],
      1:[['修正作品集最弱页面','Portfolio','根据反馈只改一个核心问题，避免无止境全盘重做。']],
      2:[['整理 6 个面试故事','Planning','用 Situation–Action–Result 记录协作、冲突、失败、创新与学习。']],
      3:[['清理岗位管线','Applications','关闭失效岗位，跟进已申请岗位，补充 2 个新机会。']],
      4:[['维护 1 位已有联系人','Networking','发送进度更新或节日问候，不索取 referral。']],
      5:[['完成 1 个高匹配申请','Applications','假期保持管线不断，但不追求数量。']],
      6:[['作品集集中修改 3–4 小时','Portfolio','统一字体、图注、页码与项目叙事；导出 Portfolio V1.1。']]
    }},
    {start:'2027-01-11',end:'2027-03-31',name:'招聘旺季与中国线启动',goal:'累计 150–200 个美国申请、80–120 个有效联系人，并启动中国游戏/创意设计线',work:{
      0:[['复盘申请漏斗并规划下周','Planning','查看申请→回复→面试转化率；决定应改岗位定位、材料还是 networking。']],
      1:[['完成 2 个美国岗位申请','Applications','优先新发布 7 天内岗位；至少一个 Spatial / Experiential / 3D。']],
      2:[['Portfolio V2 / 技能补强','Portfolio','根据本周岗位缺口补一个证据：Unreal、3D workflow、空间叙事或施工理解。']],
      3:[['完成 2 个美国岗位申请','Applications','Architecture 只作为留美保底，不挤占主线作品时间。']],
      4:[['联系 2 位从业者并跟进 1 人','Networking','一位美国目标公司联系人；一位中国游戏/创意设计联系人。']],
      5:[['完成 1 个精选申请并练习面试','Applications','提交后用英文录音回答 Tell me about yourself 和一个项目故事。']],
      6:[['深度工作：作品集或测试题 4–6 小时','Portfolio','有面试/测试时优先交付；没有时推进 Portfolio V2 与中国版作品集。'],['更新中美双轨 Tracker','Planning','比较岗位成长性、作品匹配度、城市与签证，不只看数量。']]
    }},
    {start:'2027-04-01',end:'2027-05-31',name:'面试、测试题与 Offer 管理',goal:'提高面试转化率，完成测试题，并形成可比较的中美 Offer 选项',work:{
      0:[['复盘面试表现与下周安排','Planning','记录每次问题、回答漏洞、后续动作和预计回复时间。']],
      1:[['面试准备或完成 1 个高匹配申请','Applications','有面试时研究团队与面试官；无面试时补充管线。']],
      2:[['作品测试 / Portfolio 定向调整','Portfolio','按目标岗位重排前 6 页，并准备 5 分钟与 15 分钟两个讲述版本。']],
      3:[['跟进申请与 recruiter','Networking','对 7–10 天无回复的高匹配申请发送一次简洁跟进。']],
      4:[['模拟面试 45 分钟','Planning','练习英文项目讲述、行为问题、签证说明与薪资回答，并记录改进点。']],
      5:[['补充 1–2 个精选机会','Applications','避免因进入面试就停止投递，直到书面 Offer 确认。']],
      6:[['测试题 / 面试深度准备 4–6 小时','Portfolio','围绕最近的真实机会工作；没有流程时完善最匹配项目。']]
    }},
    {start:'2027-06-01',end:'2027-06-30',name:'毕业、Offer 决策与入职',goal:'完成 OPT 与入职准备，理性比较中美机会并确定下一步',work:{
      0:[['每周决策复盘','Planning','更新 Offer / 面试状态、截止日期、风险和下周唯一关键动作。']],
      1:[['跟进最终流程与书面材料','Networking','确认面试反馈、Offer 条款或入职文件，所有承诺尽量落实为书面。']],
      2:[['OPT 与入职材料检查','Planning','核对学校国际学生办公室要求、EAD、I-9 与开始日期；以官方信息为准。']],
      3:[['比较岗位长期价值','Planning','评估职责、导师、成长、签证、城市成本、团队稳定性和作品积累。']],
      4:[['维护关键行业关系','Networking','向帮助过你的人发送简短进度更新与感谢。']],
      5:[['处理未完成流程或补充申请','Applications','在正式接受并确认入职前保持合理备选。']],
      6:[['毕业与入职准备','Planning','整理作品、交接文件、搬迁计划和入职前学习清单；保留休息。']]
    }}
  ];
  const out=[],start=new Date('2026-08-17T12:00:00'),end=new Date('2027-06-30T12:00:00');
  for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){
    const iso=d.toISOString().slice(0,10),phase=phases.find(p=>iso>=p.start&&iso<=p.end),day=d.getDay();
    if(!phase)continue;
    phase.work[day].slice(0,1).forEach((x,i)=>out.push({id:`plan-${iso}-${i}`,title:x[0].replace(/4–6 小时/g,'约 3 小时').replace(/3–4 小时/g,'约 3 小时'),category:x[1],date:iso,done:false,opportunity:/秋招|作品集|Portfolio|Hero/i.test(x[0])?'High':'Medium',readiness:'Partial',effort:day===6?180:90,note:`${phase.name}｜${x[2].replace(/4–6 小时/g,'约 3 小时').replace(/3–4 小时/g,'约 3 小时')}`}));
  }
  return out;
}
const initialData = {
  tasks: buildDailyPlan(),
  jobs: [
    {id:'j1',company:'Moment Factory',role:'Junior Multimedia Designer',country:'美国',city:'Los Angeles',direction:'Experiential',status:'准备申请',date:'',contact:'',salary:'$65k–80k',notes:'定制作品集前 6 页'},
    {id:'j2',company:'Gensler',role:'Junior Designer',country:'美国',city:'Los Angeles',direction:'Architecture',status:'准备申请',date:'',contact:'',salary:'',notes:'留美保底线'},
    {id:'j3',company:'腾讯游戏',role:'场景设计师',country:'中国',city:'深圳',direction:'Game',status:'关注',date:'',contact:'',salary:'',notes:'2027 春招'}
  ],
  contacts: [
    {id:'c1',name:'Alex Chen',company:'Experiential Studio',role:'Spatial Designer',country:'美国',channel:'LinkedIn',status:'待联系',lastDate:'',next:'发送 coffee chat 邀请',notes:'UCLA 校友示例'},
    {id:'c2',name:'Mia Wang',company:'Game Studio',role:'Environment Artist',country:'中国',channel:'微信',status:'待联系',lastDate:'',next:'询问作品集建议',notes:''}
  ],
  projects: [
    {id:'p1',name:'Unreal Environment Hero Project',type:'Game / Environment',track:'美国/中国',progress:0,deadline:'2026-11-15',next:'确定主题、参考图与首个 modular kit',notes:'核心转型项目'},
    {id:'p2',name:'Agence TER Internship',type:'Landscape / Spatial',track:'美国',progress:0,deadline:'2026-09-30',next:'收集并整理项目素材',notes:'突出专业实践'},
    {id:'p3',name:'AI-assisted Architecture Research',type:'AI / Architecture',track:'美国',progress:0,deadline:'2026-10-20',next:'建立项目叙事大纲',notes:'跨界差异化项目'},
    {id:'p4',name:'UCLA Studio Project',type:'Spatial / Experiential',track:'美国',progress:0,deadline:'2027-02-15',next:'建立每周归档流程',notes:'随课程持续更新'}
  ],
  resumes: [
    {id:'resume-us-spatial',versionName:'US Spatial / Experiential',track:'美国主线',fullName:'',headline:'Spatial Designer | 3D & Real-time Environments',email:'',phone:'',location:'Los Angeles, CA',linkedin:'',portfolio:'',summary:'',education:'University of California, Los Angeles (UCLA) | Los Angeles, US\nMaster of Science in Architecture and Urban Design | Aug 2026 - Jun 2027 (Expected)\n\nCentral South University | Changsha, China\nBachelor of Architecture | Sept 2021 - Jun 2026',experience:'Agence TER (Shanghai) Co., Ltd. | Shanghai, China\nDesign Intern | Aug 2025 - Dec 2025\n• [Describe your contribution, tools, and measurable result]',projects:'Unreal Environment Hero Project | [City]\nEnvironment / Spatial Designer | [Year]\n• [Describe the spatial narrative, workflow, and result]\n\nAI-assisted Architecture Research | [City]\nDesigner / Researcher | [Year]\n• [Describe the research question and your contribution]',activities:'',awards:'',skills:'• Design: Spatial storytelling, architectural design, visualization\n• 3D & Visualization: Blender, Unreal Engine\n• Visual Tools: Stable Diffusion, [Add Adobe / CAD tools you can demonstrate]',updatedAt:''},
    {id:'resume-us-arch',versionName:'US Architecture / Visualization',track:'美国保底',fullName:'',headline:'Architectural Designer | Visualization & Digital Design',email:'',phone:'',location:'Los Angeles, CA',linkedin:'',portfolio:'',summary:'',education:'University of California, Los Angeles (UCLA) | Los Angeles, US\nMaster of Science in Architecture and Urban Design | Aug 2026 - Jun 2027 (Expected)\n\nCentral South University | Changsha, China\nBachelor of Architecture | Sept 2021 - Jun 2026',experience:'Agence TER (Shanghai) Co., Ltd. | Shanghai, China\nDesign Intern | Aug 2025 - Dec 2025\n• [Describe project scope, drawing/modeling contribution, and result]',projects:'Selected Architecture Studio | [City]\nArchitectural Designer | [Year]\n• [Describe the design problem, your role, and final deliverables]\n\nAI-assisted Architecture Research | [City]\nDesigner / Researcher | [Year]\n• [Explain how computation or AI improved the design process]',activities:'',awards:'',skills:'• Design: Architectural design, site analysis, visualization\n• 3D & Visualization: Blender, Unreal Engine, [Add Rhino / CAD tools]\n• Languages: [Add languages and proficiency]',updatedAt:''},
    {id:'resume-cn-game',versionName:'China Game / Creative',track:'中国精选',fullName:'',headline:'3D Environment & Spatial Designer',email:'',phone:'',location:'[中国城市 / 可远程]',linkedin:'',portfolio:'',summary:'',education:'加州大学洛杉矶分校（UCLA） | 美国洛杉矶\n建筑与城市设计理学硕士 | 2026.08 - 2027.06（预计）\n\n中南大学 | 中国长沙\n建筑学五年制本科 | 2021.09 - 2026.06',experience:'Agence TER（上海） | 中国上海\n设计实习生 | 2025.08 - 2025.12\n• [用中文描述个人贡献、使用工具和成果]',projects:'Unreal Environment Hero Project | [城市]\n场景 / 空间设计 | [年份]\n• [描述场景主题、模块化流程、材质灯光和最终效果]\n\nAI-assisted Architecture Research | [城市]\n设计 / 研究 | [年份]\n• [描述研究目标和个人贡献]',activities:'',awards:'',skills:'• 3D / 实时：Blender、Unreal Engine\n• 视觉生成：Stable Diffusion\n• 设计：空间叙事、建筑设计、可视化',updatedAt:''}
  ],
  kpi: { portfolioGoal:5, applicationGoal:3, networkingGoal:3, skillGoal:2.5, portfolio:0, applications:0, networking:0, skill:0 },
  settings:{name:'',weekStart:'2026-08-10'}
};
const resumeTitleDefaults={summaryTitle:'PROFILE',educationTitle:'EDUCATION',experienceTitle:'INTERNSHIP EXPERIENCES',projectsTitle:'SELECTED PROJECTS',activitiesTitle:'EXTRACURRICULAR ACTIVITIES',awardsTitle:'HONORS & AWARDS',skillsTitle:'SKILLS'};
function normalizeResumes(resumes){return (resumes||structuredClone(initialData.resumes)).map(r=>({...resumeTitleDefaults,...r,activities:r.activities||'',awards:r.awards||''}))}
let data = load();
data.resumes=normalizeResumes(data.resumes);
let currentView='dashboard'; let selectedResumeId='resume-us-spatial';
const navItems=[['dashboard','⌂','Dashboard'],['tasks','✓','每日任务'],['resume','▤','简历中心'],['searchhub','⌕','在线搜索'],['jobs','▦','岗位 Tracker'],['network','◎','Networking'],['portfolio','◇','Portfolio'],['timeline','◷','时间线'],['strategy','⇄','双轨视图']];
const titles={dashboard:['OVERVIEW','早上好，继续向前。'],tasks:['DAILY RHYTHM','今天要完成什么？'],resume:['RESUME STUDIO','一份经历，三个清晰版本'],searchhub:['SEARCH HUB','一次搜索，打开所有渠道'],jobs:['OPPORTUNITIES','岗位 Tracker'],network:['RELATIONSHIPS','Networking Tracker'],portfolio:['CRAFT & PROOF','Portfolio 项目'],timeline:['AUG 2026 — JUN 2027','你的求职时间线'],strategy:['TWO-TRACK STRATEGY','美国优先，中国精选']};
function load(){try{let saved=JSON.parse(localStorage.getItem(STORAGE_KEY))||{},oldTasks=saved.tasks||[],oldById=new Map(oldTasks.map(t=>[t.id,t])),plans=buildDailyPlan().map(t=>({...t,done:oldById.get(t.id)?.done||false})),custom=oldTasks.filter(t=>!String(t.id).startsWith('plan-'));return {...structuredClone(initialData),...saved,tasks:[...custom,...plans]}}catch{return structuredClone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));render();}
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function init(){document.getElementById('nav').innerHTML=navItems.map(([id,icon,label])=>`<button class="nav-item" data-view="${id}"><i>${icon}</i>${label}</button>`).join('');document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());document.getElementById('nav').onclick=e=>{let b=e.target.closest('[data-view]');if(b){currentView=b.dataset.view;render()}};document.getElementById('quickAdd').onclick=()=>openModal(currentView==='dashboard'?'task':({tasks:'task',jobs:'job',network:'contact',portfolio:'project'}[currentView]||'task'));document.getElementById('updateBtn').onclick=()=>checkForUpdate(true);document.getElementById('resetDemo').title='清零并恢复计划模板';document.getElementById('resetDemo').onclick=()=>{if(confirm('确定清零所有进度？计划模板会保留，但你的打卡、KPI、投递、联系和作品集进度都会归零。')){data=structuredClone(initialData);data.resumes=normalizeResumes(data.resumes);save();toast('进度已清零，计划模板已保留')}};render();setTimeout(()=>checkForUpdate(false),2500)}
async function checkForUpdate(manual=false){if(!window.careerAtlas?.checkUpdate){if(manual)toast('当前版本不支持在线更新');return}let btn=document.getElementById('updateBtn');btn.textContent='检查中…';btn.disabled=true;let result=await window.careerAtlas.checkUpdate();btn.textContent='检查更新';btn.disabled=false;if(!result.ok){if(manual)toast('暂时无法连接更新服务器');return}if(!result.available){if(manual)toast(`已是最新版本 ${result.current}`);return}showUpdateModal(result)}
function showUpdateModal(info){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">UPDATE AVAILABLE</p><h2>发现新版本 ${esc(info.latest)}</h2></div><button class="close" type="button">×</button></div><p class="subtle">当前版本 ${esc(info.current)}。更新会保留你的任务、岗位、联系人和作品集数据。</p><div class="update-notes">${esc(info.notes||'包含功能改进与问题修复。')}</div><div class="modal-actions"><button class="secondary close" type="button">稍后</button><button class="primary" id="installUpdate" ${info.downloadUrl?'':'disabled'}>下载并重启安装</button></div></div></div>`;let root=document.getElementById('modalRoot');root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.innerHTML='');let install=root.querySelector('#installUpdate');install.onclick=async()=>{install.disabled=true;install.textContent='正在下载，请稍候…';try{await window.careerAtlas.installUpdate({downloadUrl:info.downloadUrl,assetName:info.assetName})}catch{install.disabled=false;install.textContent='重试下载';toast('更新下载失败，请稍后重试')}}}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.getElementById('pageEyebrow').textContent=titles[currentView][0];document.getElementById('pageTitle').textContent=titles[currentView][1];document.getElementById('content').innerHTML=({dashboard:dashboardView,tasks:tasksView,resume:resumeView,searchhub:searchHubView,jobs:jobsView,network:networkView,portfolio:portfolioView,timeline:timelineView,strategy:strategyView}[currentView])();bindView();if(currentView==='resume')bindResumeEditor()}
const pct=(v,g)=>Math.min(100,Math.round((v/g)*100));
const careerStages=[
  {id:'foundation',name:'Stage 1 · Foundation',start:'2026-08-15',end:'2026-09-15',focus:'先形成可被判断的职业身份，同时立即参加中国秋招。',goals:{portfolio:8,applications:3,networking:2,skill:2},weights:{Portfolio:50,Applications:25,Planning:15,Skill:10,Networking:8},mix:[['Portfolio / 定位',50,'当前最大瓶颈'],['中国秋招',25,'有截止日期，立即行动'],['美国准备 + 轻 Networking',15,'先研究与建立少量连接'],['Skill gap',10,'只学项目需要的技能']]},
  {id:'portfolio',name:'Stage 2 · Portfolio Ready',start:'2026-09-16',end:'2026-10-15',focus:'完成 Portfolio V1，并根据中国秋招反馈快速迭代。',goals:{portfolio:10,applications:5,networking:3,skill:3},weights:{Portfolio:45,Applications:30,Networking:12,Skill:10,Planning:8},mix:[['Portfolio V1',45,'Hero Environment 优先'],['中国秋招',30,'申请、测试与反馈'],['Networking',15,'有基础页面后逐步增加'],['Skill gap',10,'补 Unreal / Revit 必需项']]},
  {id:'market',name:'Stage 3 · Market Ready',start:'2026-10-16',end:'2027-03-31',focus:'从 building 转向 selling：投递、连接、面试、反馈、再迭代。',goals:{portfolio:5,applications:8,networking:5,skill:2},weights:{Applications:40,Networking:25,Portfolio:22,Planning:10,Skill:8},mix:[['Applications',40,'美国加速 + 中国持续'],['Networking',25,'开始 referral 与 recruiter'],['Portfolio',25,'按反馈定向修正'],['Interview / Skill',10,'围绕真实机会准备']]},
  {id:'interview',name:'Stage 4 · Interview',start:'2027-04-01',end:'2027-06-30',focus:'优先真实流程、测试题、面试、跟进与 Offer 决策。',goals:{portfolio:3,applications:4,networking:4,skill:1},weights:{Planning:40,Networking:28,Applications:22,Portfolio:18,Skill:5},mix:[['Interview / Tests',40,'最近的真实机会第一'],['Follow-up',25,'推进现有流程'],['Applications',20,'书面 Offer 前保持管线'],['Portfolio',15,'只做岗位定向调整']]}
];
function currentStage(date=today()){return careerStages.find(s=>date>=s.start&&date<=s.end)||careerStages[careerStages.length-1]}
function taskPriority(t){let stage=currentStage(),days=Math.ceil((new Date(t.date+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000),urgency=days<0?120:days===0?100:days<=2?70:days<=7?35:0,opportunity={High:30,Medium:15,Low:0}[t.opportunity||'Medium'],readiness={Ready:20,Partial:10,Blocked:-15}[t.readiness||'Partial'],effort=Number(t.effort||90)<=90?10:Number(t.effort||90)<=180?5:0,score=urgency+(stage.weights[t.category]||5)+opportunity+readiness+effort;if(/中国|秋招|deadline|截止|面试|测试|OA/i.test(`${t.title} ${t.note}`))score+=18;if(t.done)score-=200;return score}
function priorityTasks(rows){return [...rows].sort((a,b)=>taskPriority(b)-taskPriority(a)||a.date.localeCompare(b.date))}
function stats(){let now=new Date(today()+'T12:00:00'),day=(now.getDay()+6)%7,monday=new Date(now);monday.setDate(now.getDate()-day);let sunday=new Date(monday);sunday.setDate(monday.getDate()+6);let start=monday.toISOString().slice(0,10),end=sunday.toISOString().slice(0,10),week=data.tasks.filter(t=>t.date>=start&&t.date<=end),done=week.filter(t=>t.done).length;return {completion:week.length?pct(done,week.length):0,apps:data.jobs.filter(j=>j.status!=='关注'&&j.status!=='准备申请').length,contacts:data.contacts.filter(c=>c.status!=='待联系').length,portfolio:Math.round(data.projects.reduce((s,p)=>s+Number(p.progress),0)/(data.projects.length||1))}}
function dashboardView(){let s=stats(),k=data.kpi,stage=currentStage(),g=stage.goals,overall=Math.round([pct(k.portfolio,g.portfolio),pct(k.applications,g.applications),pct(k.networking,g.networking),pct(k.skill,g.skill)].reduce((a,b)=>a+b,0)/4),horizon=data.tasks.filter(t=>t.date>=today()&&t.date<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)),daily=priorityTasks(horizon).slice(0,4);return `<div class="stage-banner"><div><span class="tag both">${stage.name}</span><h2>${stage.focus}</h2><p>排序依据：Deadline → Readiness → Opportunity Value → Career Priority → Effort</p></div><strong>${stage.start.slice(5)} — ${stage.end.slice(5)}</strong></div><div class="grid stats">${statCard('本周完成率',s.completion+'%','✓','每日任务打卡')}${statCard('累计投递',s.apps,'↗','中美管线分开管理')}${statCard('有效联系人',s.contacts,'◎','现阶段重质量不重数量')}${statCard('作品集进度',s.portfolio+'%','◇','当前最重要的职业资产')}</div><div class="grid dashboard-grid"><div class="grid"><div class="card"><div class="card-head"><div><h2>阶段自适应 KPI</h2><span class="subtle">目标会随 readiness stage 自动变化</span></div><button class="secondary" data-action="edit-kpi">更新数据</button></div><div class="kpi-wrap"><div class="progress-ring" style="--p:${overall}"><div class="ring-copy"><strong>${overall}%</strong><span>WEEKLY</span></div></div><div class="kpi-list">${kpiRow('Portfolio hours',k.portfolio,g.portfolio,'h')}${kpiRow('Applications',k.applications,g.applications,'')}${kpiRow('Networking',k.networking,g.networking,'')}${kpiRow('Skill hours',k.skill,g.skill,'h')}</div></div></div><div class="card"><div class="card-head"><div><h2>智能优先队列</h2><span class="subtle">未来 7 天按截止日期和阶段价值排序</span></div><button class="secondary" data-action="add-task">＋ 添加</button></div><div class="task-list">${daily.map(taskHtml).join('')||empty('未来 7 天没有任务')}</div></div></div><div class="grid"><div class="card"><div class="card-head"><h2>当前阶段投入</h2><span class="subtle">动态权重</span></div><div class="mini-list">${stage.mix.map(x=>direction(...x)).join('')}</div></div><div class="card readiness-card"><div class="card-head"><h2>当前检查点</h2><span class="tag">SEP 15</span></div>${readinessItem('CV V1 + UCLA 信息',resumeCompletion(data.resumes?.[0]||{})>=45)}${readinessItem('LinkedIn V1 可被查看',!!data.resumes?.[0]?.linkedin)}${readinessItem('Portfolio V0.5',s.portfolio>=25)}${readinessItem('中国秋招已开始投递',data.jobs.some(j=>j.country==='中国'&&!['关注','准备申请'].includes(j.status)))}${readinessItem('Unreal Hero Project 已启动',(data.projects.find(p=>/Unreal/i.test(p.name))?.progress||0)>0)}</div></div></div>`}
function readinessItem(label,done){return `<div class="readiness-item ${done?'done':''}"><span>${done?'✓':'○'}</span><b>${label}</b></div>`}
function statCard(label,val,icon,note){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${val}</div><div class="trend">${note}</div></div>`}
function kpiRow(label,v,g,u){return `<div class="kpi-row"><div class="kpi-meta"><span>${label}</span><b>${v}${u} / ${g}${u}</b></div><div class="bar"><span style="width:${pct(v,g)}%"></span></div></div>`}
function direction(label,p,n){return `<div class="direction-card"><div class="direction-head"><strong>${label}</strong><span>${p}%</span></div><div class="bar"><span style="width:${p}%"></span></div><p class="subtle">${n}</p></div>`}
function taskHtml(t){let p=taskPriority(t),level=p>=150?'P1':p>=100?'P2':'P3';return `<div class="task ${t.done?'done':''}"><span class="check" data-action="toggle-task" data-id="${t.id}">${t.done?'✓':''}</span><div class="task-copy"><div class="task-title">${esc(t.title)}</div><div class="task-note">${esc(t.date||'')} · ${esc(t.note||'')}</div></div><span class="priority ${level.toLowerCase()}">${level}</span><span class="tag">${esc(t.category)}</span><span class="row-actions"><button data-action="edit-task" data-id="${t.id}">✎</button><button data-action="delete-task" data-id="${t.id}">×</button></span></div>`}
function visibleTasks(range='week',category='全部类别'){let start=today(),end=start;if(range==='week'){let d=new Date(start+'T12:00:00');d.setDate(d.getDate()+6);end=d.toISOString().slice(0,10)}else if(range==='all'){start='0000-00-00';end='9999-99-99'}return priorityTasks(data.tasks.filter(t=>t.date>=start&&t.date<=end&&(category==='全部类别'||t.category===category)))}
function tasksView(){let rows=visibleTasks(),stage=currentStage();return `<div class="stage-strip"><b>${stage.name}</b><span>${stage.focus}</span></div><div class="toolbar"><select id="dateFilter"><option value="today">今天</option><option value="week" selected>未来 7 天</option><option value="all">全部日期</option></select><select id="taskFilter"><option>全部类别</option>${['Portfolio','Applications','Networking','Skill','Planning'].map(x=>`<option>${x}</option>`)}</select><button class="primary" data-action="add-task">＋ 添加任务</button></div><div class="card"><div class="card-head"><div><h2>动态优先任务</h2><span class="subtle">P1 立即处理 · P2 本周关键 · P3 阶段常规；可编辑机会价值、准备度和预计时间</span></div><span class="tag" id="taskCount">${rows.filter(t=>t.done).length} / ${rows.length} 完成</span></div><div class="task-list" id="allTasks">${rows.map(taskHtml).join('')||empty('这个日期范围还没有任务')}</div></div>`}
function resumeCompletion(r){let checks=[r.fullName,r.email,r.phone,r.education,r.experience,r.projects,r.skills];return Math.round(checks.filter(x=>String(x||'').trim()&&!String(x).includes('[')).length/checks.length*100)}
function resumeLine(line,index){let clean=line.trim();if(/^[•-]/.test(clean))return `<p class="pv-bullet">• ${esc(clean.replace(/^[•-]\s*/,''))}</p>`;let parts=clean.split(/\s+\|\s+/),left=parts.shift(),right=parts.join(' | ');return `<div class="pv-row ${index===0?'primary':'secondary'}"><span>${esc(left)}</span>${right?`<span>${esc(right)}</span>`:''}</div>`}
function previewSection(title,content){if(!String(content||'').trim())return'';let groups=String(content).trim().split(/\r?\n\s*\r?\n/);return `<section>${String(title||'').trim()?`<h4>${esc(title)}</h4>`:''}${groups.map(group=>`<div class="pv-group">${group.split(/\r?\n/).filter(Boolean).map((line,i)=>resumeLine(line,i)).join('')}</div>`).join('')}</section>`}
function resumePreview(r){let contact=[r.location,r.phone,r.email,r.linkedin,r.portfolio].filter(Boolean).join('  |  ');return `<div class="resume-paper"><div class="resume-name">${esc(r.fullName||'YOUR NAME')}</div><div class="resume-contact">${esc(contact)}</div>${r.summary?previewSection(r.summaryTitle??'PROFILE',r.summary):''}${previewSection(r.educationTitle??'EDUCATION',r.education)}${previewSection(r.experienceTitle??'INTERNSHIP EXPERIENCES',r.experience)}${previewSection(r.projectsTitle??'SELECTED PROJECTS',r.projects)}${previewSection(r.activitiesTitle??'EXTRACURRICULAR ACTIVITIES',r.activities)}${previewSection(r.awardsTitle??'HONORS & AWARDS',r.awards)}${previewSection(r.skillsTitle??'SKILLS',r.skills)}</div>`}
function resumeView(){let resumes=data.resumes||initialData.resumes,r=resumes.find(x=>x.id===selectedResumeId)||resumes[0];selectedResumeId=r.id;return `<div class="resume-layout"><aside class="grid resume-versions">${resumes.map(x=>`<button class="resume-version ${x.id===r.id?'active':''}" data-action="select-resume" data-id="${x.id}"><span class="tag ${x.track.includes('中国')?'cn':'us'}">${esc(x.track)}</span><strong>${esc(x.versionName)}</strong><div class="bar"><span style="width:${resumeCompletion(x)}%"></span></div><small>${resumeCompletion(x)}% 完成</small></button>`).join('')}<div class="card resume-tip"><h3>栏目完全可编辑</h3><p>浅色输入框是打印出来的栏目标题。每段内容用空行分隔；使用 <b>机构 | 地点</b> 可自动左右对齐。</p></div></aside><div class="card resume-editor"><div class="card-head"><div><h2>${esc(r.versionName)}</h2><span class="subtle">标题与内容都会自动保存在本机</span></div><span class="tag" id="resumeCompletion">${resumeCompletion(r)}% 完成</span></div><form id="resumeForm" class="resume-form">${resumeField('fullName','姓名',r.fullName,'text')}${resumeField('headline','职业标题（仅用于版本管理，不显示在版面）',r.headline,'text','full')}${resumeField('email','Email',r.email,'email')}${resumeField('phone','电话',r.phone,'text')}${resumeField('location','城市',r.location,'text')}${resumeField('linkedin','LinkedIn',r.linkedin,'url')}${resumeField('portfolio','Portfolio URL',r.portfolio,'url','full')}${resumeSectionEditor('summaryTitle','summary',r.summaryTitle,r.summary,'可选栏目','')}${resumeSectionEditor('educationTitle','education',r.educationTitle,r.education,'栏目标题','tall')}${resumeSectionEditor('experienceTitle','experience',r.experienceTitle,r.experience,'栏目标题','tall')}${resumeSectionEditor('projectsTitle','projects',r.projectsTitle,r.projects,'栏目标题','tall')}${resumeSectionEditor('activitiesTitle','activities',r.activitiesTitle,r.activities,'栏目标题','tall')}${resumeSectionEditor('awardsTitle','awards',r.awardsTitle,r.awards,'栏目标题','')}${resumeSectionEditor('skillsTitle','skills',r.skillsTitle,r.skills,'栏目标题','')}</form></div><div class="resume-preview-col"><div class="card-head resume-export-head"><div><h2>实时预览</h2><span class="subtle">栏目标题、细横线与导出文件同步</span></div></div><div id="resumePreview">${resumePreview(r)}</div><div class="resume-export"><button class="secondary" data-action="resume-word">导出 Word</button><button class="primary" data-action="resume-pdf">导出 PDF</button></div></div></div>`}
function resumeSectionEditor(titleKey,contentKey,title,content,label,extra=''){return `<div class="field full resume-section-editor ${extra}"><label>${label}</label><input class="section-title-input" name="${titleKey}" value="${esc(title||'')}" placeholder="输入自定义栏目标题"><textarea name="${contentKey}" placeholder="输入这一栏的内容">${esc(content||'')}</textarea></div>`}
function resumeField(name,label,value,type,extra=''){let control=type==='textarea'?`<textarea name="${name}">${esc(value||'')}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value||'')}">`;return `<div class="field ${extra}"><label>${label}</label>${control}</div>`}
function currentResume(){return (data.resumes||[]).find(x=>x.id===selectedResumeId)}
function bindResumeEditor(){let form=document.getElementById('resumeForm');if(!form)return;form.oninput=()=>{let r=currentResume();new FormData(form).forEach((value,key)=>r[key]=String(value));r.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));document.getElementById('resumePreview').innerHTML=resumePreview(r);document.getElementById('resumeCompletion').textContent=`${resumeCompletion(r)}% 完成`}}
const columns={jobs:[['company','公司'],['role','岗位'],['place','国家 / 城市'],['direction','方向'],['status','状态'],['date','投递日期'],['contact','联系人'],['salary','薪资']],contacts:[['name','姓名'],['company','公司'],['role','职位'],['country','国家'],['channel','渠道'],['status','状态'],['lastDate','最近联系'],['next','下一步']]};
function searchHubView(){return `<div class="card search-hero"><div><span class="tag us">官方页面登录</span><h2>招聘与联系人搜索中心</h2><p class="subtle">输入一次关键词，再选择要打开的平台。搜索和登录发生在官方网页中，Career Atlas 不保存密码。</p></div><div class="search-form"><div class="field"><label>岗位 / 技能 / 公司关键词</label><input id="onlineQuery" value="Spatial Designer" placeholder="例如 Spatial Designer / Unreal / Gensler"></div><div class="field"><label>城市（LinkedIn 使用）</label><input id="onlineLocation" value="Los Angeles" placeholder="例如 Los Angeles"></div></div></div><div class="grid search-grid"><div class="card source-card"><span class="source-logo linkedin">in</span><div><h3>LinkedIn Jobs</h3><p>搜索美国岗位，并使用过去一周、经验等级等官方筛选。</p></div><button class="primary" data-action="open-search" data-platform="linkedin-jobs">搜索岗位 ↗</button></div><div class="card source-card"><span class="source-logo linkedin">in</span><div><h3>LinkedIn People</h3><p>搜索 UCLA 校友、目标公司设计师和 recruiter。</p></div><button class="primary" data-action="open-search" data-platform="linkedin-people">搜索联系人 ↗</button></div><div class="card source-card"><span class="source-logo handshake">H</span><div><h3>UCLA Handshake</h3><p>打开学生职位搜索；登录后在站内继续使用学校筛选。</p></div><button class="primary" data-action="open-search" data-platform="handshake">打开 Handshake ↗</button></div><div class="card source-card"><span class="source-logo twelve">12</span><div><h3>UCLA 12Twenty</h3><p>打开 UCLA 职业系统；登录后搜索职位、活动和校友资源。</p></div><button class="primary" data-action="open-search" data-platform="12twenty">打开 12Twenty ↗</button></div></div><div class="card capture-card"><div><h2>找到结果后快速保存</h2><p class="subtle">把官方网页留在浏览器中，回到这里用简短表单保存关键内容即可。</p></div><div><button class="secondary" data-action="add-contact">＋ 保存联系人</button> <button class="primary" data-action="add-job">＋ 保存岗位</button></div></div>`}
function openOnlineSearch(platform){let q=encodeURIComponent(document.getElementById('onlineQuery')?.value.trim()||''),loc=encodeURIComponent(document.getElementById('onlineLocation')?.value.trim()||'');let urls={'linkedin-jobs':`https://www.linkedin.com/jobs/search/?keywords=${q}&location=${loc}`,'linkedin-people':`https://www.linkedin.com/search/results/people/?keywords=${q}%20UCLA`,'handshake':`https://app.joinhandshake.com/stu/postings?query=${q}`,'12twenty':'https://ucla.12twenty.com/'};let url=urls[platform];if(window.careerAtlas)window.careerAtlas.openExternal(url).catch(()=>toast('无法打开网页，请检查默认浏览器'));else window.open(url,'_blank')}
function jobsView(){return trackerView('jobs','搜索公司或岗位…','添加岗位','job')}
function networkView(){return trackerView('contacts','搜索姓名或公司…','添加联系人','contact')}
function trackerView(type,placeholder,addLabel,entity){let rows=data[type];return `<div class="toolbar"><input id="search" placeholder="${placeholder}"><select id="trackFilter"><option value="">全部</option>${type==='jobs'?['美国','中国'].map(x=>`<option>${x}</option>`).join(''):['待联系','已联系','保持联系'].map(x=>`<option>${x}</option>`).join('')}</select><button class="secondary" data-action="export" data-type="${type}">⇩ 导出 CSV</button><button class="primary" data-action="add-${entity}">＋ ${addLabel}</button></div><div class="card table-card"><table><thead><tr>${columns[type].map(c=>`<th>${c[1]}</th>`).join('')}<th></th></tr></thead><tbody id="trackerBody">${trackerRows(type,rows)}</tbody></table></div>`}
function trackerRows(type,rows){if(!rows.length)return `<tr><td colspan="9">${empty('还没有记录')}</td></tr>`;return rows.map(r=>`<tr>${columns[type].map(([key])=>{let value=key==='place'?`${r.country} · ${r.city}`:r[key];return `<td>${key==='status'?`<span class="status ${esc(value)}">${esc(value)}</span>`:esc(value||'—')}</td>`}).join('')}<td class="row-actions"><button data-action="edit-${type==='jobs'?'job':'contact'}" data-id="${r.id}">✎</button><button data-action="delete-${type==='jobs'?'job':'contact'}" data-id="${r.id}">×</button></td></tr>`).join('')}
function portfolioView(){return `<div class="toolbar"><span class="subtle">把建筑训练转化为空间叙事、实时 3D 与视觉设计能力。</span><button class="secondary" data-action="export" data-type="projects">⇩ 导出 CSV</button><button class="primary" data-action="add-project">＋ 添加项目</button></div><div class="grid portfolio-grid">${data.projects.map(p=>`<div class="card project-card"><div class="project-top"><span class="tag ${p.track==='美国'?'us':p.track==='中国'?'cn':'both'}">${esc(p.track)}</span><span class="row-actions"><button data-action="edit-project" data-id="${p.id}">✎</button><button data-action="delete-project" data-id="${p.id}">×</button></span></div><h3>${esc(p.name)}</h3><span class="subtle">${esc(p.type)} · ${esc(p.deadline)}</span><p>下一步：${esc(p.next)}</p><div class="project-progress"><span>Progress</span><b>${p.progress}%</b></div><div class="bar"><span style="width:${p.progress}%"></span></div></div>`).join('')||empty('还没有作品集项目')}</div>`}
function timelineView(){let milestones=[['2026.08.15 — 09.15','Stage 1 · Foundation',['CV V1、LinkedIn V1、Portfolio V0.5','中国游戏/设计秋招立即投递','Unreal Hero Project 启动；Networking 每周 2–3 人']],['2026.09.16 — 10.15','Stage 2 · Portfolio Ready',['Hero Environment 推进至 60–100%','根据中国 OA / 测试 / 面试反馈迭代','Portfolio V1 可支持美国正式申请']],['2026.10.16 — 2027.03','Stage 3 · Market Ready',['美国 Applications + Networking 加速','维持中国游戏 / Creative 机会管线','Apply → Interview → Improve → Apply']],['2027.04 — 05','Stage 4 · Interview',['测试题、面试与 follow-up 优先','书面 Offer 前保持适量投递','比较职责、成长、签证、团队与城市成本']],['2027.06','Offer 决策与入职',['比较美国 Spatial / Architecture / Game 与中国 Game / Creative','确认 OPT、岗位与学位相关性及入职材料']]];let stage=currentStage();return `<div class="card timeline">${milestones.map((m,i)=>`<div class="milestone ${careerStages[i]?.id===stage.id?'active':''}"><span class="tag">${m[0]}</span><h3 style="margin-top:10px">${m[1]}</h3><ul>${m[2].map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div>`}
function strategyView(){let stage=currentStage();return `<div class="stage-banner"><div><span class="tag both">${stage.name}</span><h2>${stage.focus}</h2><p>当前策略不是固定比例；系统会根据 readiness 和真实截止日期调整。</p></div></div><div class="grid strategy-grid"><div class="card strategy-panel us-panel"><span class="tag us">美国 · 长期第一目标</span><h2>现在准备，Portfolio V1 后加速</h2><p class="subtle">Architecture-trained Spatial / Environment Designer 是统一职业身份。</p><ul><li>主攻 Spatial / Experiential / Real-time / Visualization</li><li>Architecture + Visualization 是 STEM/OPT 解释更自然的保底线</li><li>Game Environment / Worldbuilding 是高回报冲刺线</li><li>当前 Research &gt; Applications；10 月后 Applications + Networking 提速</li><li>补 Revit 基础，但不投入成为 BIM 专家</li></ul></div><div class="card strategy-panel cn-panel"><span class="tag cn">中国 · 现在同步主战场</span><h2>2027 秋招立即行动</h2><p class="subtle">批次制、有截止日期，不能等 Portfolio 100% 或等到 2027 年春季。</p><ul><li>只投 Game Environment、场景设计、游戏空间、3D Creative</li><li>使用 Portfolio V0.5 先投，根据测试和面试反馈继续改</li><li>记录每家公司岗位数量限制、作品集要求与截止日期</li><li>不投中国传统建筑</li></ul></div></div><div class="card priority-logic"><h2>动态排序算法</h2><div class="logic-flow"><span>1 · Deadline</span><b>→</b><span>2 · Readiness</span><b>→</b><span>3 · Opportunity Value</span><b>→</b><span>4 · Career Priority</span><b>→</b><span>5 · Effort</span></div></div>`}
function empty(s){return `<div class="empty">${s}</div>`}
function bindView(){document.getElementById('content').onclick=async e=>{let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action,id=b.dataset.id;if(a==='toggle-task'){let t=data.tasks.find(x=>x.id===id);t.done=!t.done;save()}else if(a==='open-search')openOnlineSearch(b.dataset.platform);else if(a==='select-resume'){selectedResumeId=id;render()}else if(a==='resume-word'){let r=await window.careerAtlas.exportResumeWord(currentResume());if(!r.canceled)toast('Word 简历已导出')}else if(a==='resume-pdf'){let r=await window.careerAtlas.exportResumePdf(currentResume());if(!r.canceled)toast('PDF 简历已导出')}else if(a.startsWith('add-'))openModal(a.slice(4));else if(a.startsWith('edit-'))openModal(a.slice(5),id);else if(a.startsWith('delete-'))remove(a.slice(7),id);else if(a==='edit-kpi')openModal('kpi');else if(a==='export')exportCsv(b.dataset.type)};let search=document.getElementById('search'),filter=document.getElementById('trackFilter');if(search){let run=()=>{let type=currentView==='jobs'?'jobs':'contacts',q=search.value.toLowerCase(),f=filter.value;let rows=data[type].filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)&&(type==='jobs'?(!f||r.country===f):(!f||r.status===f)));document.getElementById('trackerBody').innerHTML=trackerRows(type,rows)};search.oninput=run;filter.onchange=run}let tf=document.getElementById('taskFilter'),df=document.getElementById('dateFilter');if(tf&&df){let run=()=>{let rows=visibleTasks(df.value,tf.value);document.getElementById('allTasks').innerHTML=rows.map(taskHtml).join('')||empty('这个筛选范围还没有任务');document.getElementById('taskCount').textContent=`${rows.filter(t=>t.done).length} / ${rows.length} 完成`};tf.onchange=run;df.onchange=run}}
function remove(type,id){let map={task:'tasks',job:'jobs',contact:'contacts',project:'projects'},key=map[type];if(confirm('确定删除这条记录？')){data[key]=data[key].filter(x=>x.id!==id);save();toast('已删除')}}
const forms={
 task:{title:'任务',key:'tasks',fields:[['title','任务名称','text'],['category','类别','select',['Portfolio','Applications','Networking','Skill','Planning']],['date','截止 / 执行日期','date'],['opportunity','机会价值','select',['High','Medium','Low']],['readiness','准备度','select',['Ready','Partial','Blocked']],['effort','预计分钟','number'],['note','说明','textarea']]},
 job:{title:'岗位',key:'jobs',fields:[['company','公司','text'],['role','岗位','text'],['country','国家','select',['美国','中国']],['city','城市','text'],['direction','方向','select',['Experiential','Spatial / 3D','Game','Architecture','Visualization','AI / Creative']],['status','状态','select',['关注','准备申请','已申请','面试中','Offer','拒绝']],['date','投递日期','date'],['contact','联系人','text'],['salary','薪资','text'],['notes','备注','textarea']]},
 contact:{title:'联系人',key:'contacts',fields:[['name','姓名','text'],['company','公司','text'],['role','职位','text'],['country','国家','select',['美国','中国']],['channel','渠道','select',['LinkedIn','Email','微信','校友活动','其他']],['status','状态','select',['待联系','已联系','保持联系']],['lastDate','最近联系','date'],['next','下一步','text'],['notes','备注','textarea']]},
 project:{title:'作品集项目',key:'projects',fields:[['name','项目名称','text'],['type','类型 / 方向','text'],['track','轨道','select',['美国','中国','美国/中国']],['progress','进度 %','number'],['deadline','目标日期','date'],['next','下一步行动','text'],['notes','备注','textarea']]}
};
function openModal(type,id){if(type==='kpi')return kpiModal();let f=forms[type]||forms.task,item=id?data[f.key].find(x=>x.id===id):{};document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="editForm"><div class="modal-head"><div><p class="eyebrow">${id?'EDIT':'NEW'}</p><h2>${id?'编辑':'添加'}${f.title}</h2></div><button class="close" type="button">×</button></div><div class="form-grid">${f.fields.map(([key,label,input,opts])=>fieldHtml(key,label,input,opts,item[key])).join('')}</div><div class="modal-actions"><button class="secondary close" type="button">取消</button><button class="primary" type="submit">保存</button></div></form></div>`;wireModal(form=>{let obj={...item,id:item.id||uid()};f.fields.forEach(([key,,input])=>obj[key]=input==='number'?Number(form.elements[key].value):form.elements[key].value);if(!id&&type==='task')obj.done=false;if(id)data[f.key]=data[f.key].map(x=>x.id===id?obj:x);else data[f.key].unshift(obj);save();toast('已保存')})}
function fieldHtml(key,label,type,opts,val=''){let full=type==='textarea'?' full':'';let control=type==='select'?`<select name="${key}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${key}">${esc(val)}</textarea>`:`<input name="${key}" type="${type}" value="${esc(val)}" ${key==='progress'?'min="0" max="100"':''}>`;return `<div class="field${full}"><label>${label}</label>${control}</div>`}
function kpiModal(){let k=data.kpi;document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="editForm"><div class="modal-head"><div><p class="eyebrow">WEEKLY CHECK-IN</p><h2>更新本周 KPI</h2></div><button class="close" type="button">×</button></div><div class="form-grid">${[['portfolio','Portfolio hours'],['applications','Applications'],['networking','Networking'],['skill','Skill hours']].map(([key,l])=>fieldHtml(key,l,'number',null,k[key])).join('')}</div><div class="modal-actions"><button class="secondary close" type="button">取消</button><button class="primary">保存</button></div></form></div>`;wireModal(form=>{['portfolio','applications','networking','skill'].forEach(x=>data.kpi[x]=Number(form.elements[x].value));save();toast('本周进度已更新')})}
function wireModal(onSubmit){let root=document.getElementById('modalRoot');root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.innerHTML='');root.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))root.innerHTML=''};root.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(e.target);root.innerHTML=''}}
function exportCsv(type){let rows=data[type],cols=type==='jobs'?['company','role','country','city','direction','status','date','contact','salary','notes']:type==='contacts'?['name','company','role','country','channel','status','lastDate','next','notes']:['name','type','track','progress','deadline','next','notes'];let csv=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replace(/"/g,'""')}"`).join(','))].join('\r\n');let names={jobs:'Career-Atlas-Jobs.csv',contacts:'Career-Atlas-Networking.csv',projects:'Career-Atlas-Portfolio.csv'};if(window.careerAtlas)window.careerAtlas.exportCsv({filename:names[type],content:csv}).then(r=>!r.canceled&&toast('CSV 已导出'));else{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download=names[type];a.click();toast('CSV 已导出')}}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
