const STORAGE_KEY = 'career-atlas-v1';
const uid = () => Date.now().toString(36) + Math.random().toString(36).slice(2,6);
const today = () => new Date().toISOString().slice(0,10);

function buildDailyPlan(){
  const phases=[
    {start:'2026-08-15',end:'2026-09-30',name:'定位与基础建设',goal:'完成 CV、LinkedIn、作品集结构，并建立首批 30 家目标公司',work:{
      0:[['复盘本周并安排下周 3 个关键结果','Planning','检查实际完成量；把未完成任务重新排期，不堆积。']],
      1:[['推进一个作品集项目','Portfolio','完成一个可见产出：选图、版式、文字或图面，不只做整理。'],['记录本周 Portfolio 时间','Planning','当天结束后更新 Dashboard KPI。']],
      2:[['完成一个实时 3D 小产出','Skill','Blender / Unreal：建模、材质、灯光三者只攻一个，并保存 before/after。']],
      3:[['研究 2 家目标公司与 2 个岗位','Applications','记录岗位要求、作品集风格、签证线索和可联系的人。'],['更新岗位 Tracker','Planning','只保存真正匹配 Spatial / Experiential / 3D / Architecture 的机会。']],
      4:[['联系 1–2 位行业人士','Networking','优先 UCLA 校友和目标公司的中国从业者；发送个性化短消息。'],['准备 1 个 coffee chat 问题','Networking','问题围绕岗位、作品集标准或团队工作方式。']],
      5:[['完成 1 个高质量申请','Applications','针对岗位调整 CV 顶部和作品集项目顺序；提交后立即登记。']],
      6:[['作品集深度工作 4–6 小时','Portfolio','推进本周最重要项目，结束前导出一版 PDF 或 3 张可展示画面。'],['整理本周成果文件','Planning','按日期归档源文件、渲染图和过程截图。']]
    }},
    {start:'2026-10-01',end:'2026-12-15',name:'作品集 V1 与稳定投递',goal:'完成 Unreal Hero Project、Portfolio V1、100 家目标公司并形成稳定投递节奏',work:{
      0:[['周复盘：作品、申请与人脉','Planning','核对本周 KPI；为下周选定一个作品集硬产出和 5 个岗位。']],
      1:[['Portfolio V1 页面制作','Portfolio','完成 1–2 个可交付页面，优先讲清问题、过程、个人贡献和结果。']],
      2:[['Unreal Hero Project 制作','Skill','按 modular kit → materials → lighting → cinematic 的顺序推进并截图记录。']],
      3:[['筛选并录入 3 个匹配岗位','Applications','主攻 Spatial / Experiential / 3D；Architecture 只投高匹配留美保底岗位。']],
      4:[['发送 2 条定制 networking 消息','Networking','至少一位 UCLA 校友；记录联系日期和明确的下一步。']],
      5:[['完成 2 个岗位申请','Applications','一个深度定制、一个标准化申请；检查关键词和文件名。']],
      6:[['作品集深度工作 4–6 小时','Portfolio','完成本周页面或 Hero Project milestone；导出并在不同屏幕检查。'],['收集一次外部反馈','Portfolio','请同学、导师或从业者只回答：定位是否清楚、最弱页面是哪一页。']]
    }},
    {start:'2026-12-16',end:'2027-01-10',name:'冬季整理与面试基础',goal:'修正 Portfolio V1、整理申请材料并建立面试故事库',work:{
      0:[['轻量周复盘与休息','Planning','保留恢复时间，只安排下周最重要的 3 件事。']],
      1:[['修正作品集最弱页面','Portfolio','根据反馈只改一个核心问题，避免无止境全盘重做。']],
      2:[['整理 6 个面试故事','Planning','用 Situation–Action–Result 记录协作、冲突、失败、创新与学习。']],
      3:[['清理岗位管线','Applications','关闭失效岗位，跟进已申请岗位，补充 2 个新机会。']],
      4:[['维护 1 位已有联系人','Networking','发送进度更新或节日问候，不索取 referral。']],
      5:[['完成 1 个高匹配申请','Applications','假期保持管线不断，但不追求数量。']],
      6:[['作品集集中修改 3–4 小时','Portfolio','统一字体、图注、页码与项目叙事；导出 Portfolio V1.1。']]
    }},
    {start:'2027-01-11',end:'2027-03-31',name:'招聘旺季与中国线启动',goal:'累计 150–200 个美国申请、80–120 个有效联系人，并启动中国游戏/创意设计线',work:{
      0:[['复盘申请漏斗并规划下周','Planning','查看申请→回复→面试转化率；决定应改岗位定位、材料还是 networking。']],
      1:[['完成 2 个美国岗位申请','Applications','优先新发布 7 天内岗位；至少一个 Spatial / Experiential / 3D。']],
      2:[['Portfolio V2 / 技能补强','Portfolio','根据本周岗位缺口补一个证据：Unreal、3D workflow、空间叙事或施工理解。']],
      3:[['完成 2 个美国岗位申请','Applications','Architecture 只作为留美保底，不挤占主线作品时间。']],
      4:[['联系 2 位从业者并跟进 1 人','Networking','一位美国目标公司联系人；一位中国游戏/创意设计联系人。']],
      5:[['完成 1 个精选申请并练习面试','Applications','提交后用英文录音回答 Tell me about yourself 和一个项目故事。']],
      6:[['深度工作：作品集或测试题 4–6 小时','Portfolio','有面试/测试时优先交付；没有时推进 Portfolio V2 与中国版作品集。'],['更新中美双轨 Tracker','Planning','比较岗位成长性、作品匹配度、城市与签证，不只看数量。']]
    }},
    {start:'2027-04-01',end:'2027-05-31',name:'面试、测试题与 Offer 管理',goal:'提高面试转化率，完成测试题，并形成可比较的中美 Offer 选项',work:{
      0:[['复盘面试表现与下周安排','Planning','记录每次问题、回答漏洞、后续动作和预计回复时间。']],
      1:[['面试准备或完成 1 个高匹配申请','Applications','有面试时研究团队与面试官；无面试时补充管线。']],
      2:[['作品测试 / Portfolio 定向调整','Portfolio','按目标岗位重排前 6 页，并准备 5 分钟与 15 分钟两个讲述版本。']],
      3:[['跟进申请与 recruiter','Networking','对 7–10 天无回复的高匹配申请发送一次简洁跟进。']],
      4:[['模拟面试 45 分钟','Planning','练习英文项目讲述、行为问题、签证说明与薪资回答，并记录改进点。']],
      5:[['补充 1–2 个精选机会','Applications','避免因进入面试就停止投递，直到书面 Offer 确认。']],
      6:[['测试题 / 面试深度准备 4–6 小时','Portfolio','围绕最近的真实机会工作；没有流程时完善最匹配项目。']]
    }},
    {start:'2027-06-01',end:'2027-06-30',name:'毕业、Offer 决策与入职',goal:'完成 OPT 与入职准备，理性比较中美机会并确定下一步',work:{
      0:[['每周决策复盘','Planning','更新 Offer / 面试状态、截止日期、风险和下周唯一关键动作。']],
      1:[['跟进最终流程与书面材料','Networking','确认面试反馈、Offer 条款或入职文件，所有承诺尽量落实为书面。']],
      2:[['OPT 与入职材料检查','Planning','核对学校国际学生办公室要求、EAD、I-9 与开始日期；以官方信息为准。']],
      3:[['比较岗位长期价值','Planning','评估职责、导师、成长、签证、城市成本、团队稳定性和作品积累。']],
      4:[['维护关键行业关系','Networking','向帮助过你的人发送简短进度更新与感谢。']],
      5:[['处理未完成流程或补充申请','Applications','在正式接受并确认入职前保持合理备选。']],
      6:[['毕业与入职准备','Planning','整理作品、交接文件、搬迁计划和入职前学习清单；保留休息。']]
    }}
  ];
  const out=[],start=new Date('2026-08-17T12:00:00'),end=new Date('2027-06-30T12:00:00');
  for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){
    const iso=d.toISOString().slice(0,10),phase=phases.find(p=>iso>=p.start&&iso<=p.end),day=d.getDay();
    if(!phase)continue;
    phase.work[day].slice(0,1).forEach((x,i)=>out.push({id:`plan-${iso}-${i}`,title:x[0].replace(/4–6 小时/g,'约 3 小时').replace(/3–4 小时/g,'约 3 小时'),category:x[1],date:iso,done:false,note:`${phase.name}｜${x[2].replace(/4–6 小时/g,'约 3 小时').replace(/3–4 小时/g,'约 3 小时')}`}));
  }
  return out;
}
const initialData = {
  tasks: buildDailyPlan(),
  jobs: [
    {id:'j1',company:'Moment Factory',role:'Junior Multimedia Designer',country:'美国',city:'Los Angeles',direction:'Experiential',status:'准备申请',date:'',contact:'',salary:'$65k–80k',notes:'定制作品集前 6 页'},
    {id:'j2',company:'Gensler',role:'Junior Designer',country:'美国',city:'Los Angeles',direction:'Architecture',status:'准备申请',date:'',contact:'',salary:'',notes:'留美保底线'},
    {id:'j3',company:'腾讯游戏',role:'场景设计师',country:'中国',city:'深圳',direction:'Game',status:'关注',date:'',contact:'',salary:'',notes:'2027 春招'}
  ],
  contacts: [
    {id:'c1',name:'Alex Chen',company:'Experiential Studio',role:'Spatial Designer',country:'美国',channel:'LinkedIn',status:'待联系',lastDate:'',next:'发送 coffee chat 邀请',notes:'UCLA 校友示例'},
    {id:'c2',name:'Mia Wang',company:'Game Studio',role:'Environment Artist',country:'中国',channel:'微信',status:'待联系',lastDate:'',next:'询问作品集建议',notes:''}
  ],
  projects: [
    {id:'p1',name:'Unreal Environment Hero Project',type:'Game / Environment',track:'美国/中国',progress:0,deadline:'2026-11-15',next:'确定主题、参考图与首个 modular kit',notes:'核心转型项目'},
    {id:'p2',name:'Agence TER Internship',type:'Landscape / Spatial',track:'美国',progress:0,deadline:'2026-09-30',next:'收集并整理项目素材',notes:'突出专业实践'},
    {id:'p3',name:'AI-assisted Architecture Research',type:'AI / Architecture',track:'美国',progress:0,deadline:'2026-10-20',next:'建立项目叙事大纲',notes:'跨界差异化项目'},
    {id:'p4',name:'UCLA Studio Project',type:'Spatial / Experiential',track:'美国',progress:0,deadline:'2027-02-15',next:'建立每周归档流程',notes:'随课程持续更新'}
  ],
  kpi: { portfolioGoal:5, applicationGoal:3, networkingGoal:3, skillGoal:2.5, portfolio:0, applications:0, networking:0, skill:0 },
  settings:{name:'',weekStart:'2026-08-10'}
};
let data = load(); let currentView='dashboard';
const navItems=[['dashboard','⌂','Dashboard'],['tasks','✓','每日任务'],['searchhub','⌕','在线搜索'],['jobs','▦','岗位 Tracker'],['network','◎','Networking'],['portfolio','◇','Portfolio'],['timeline','◷','时间线'],['strategy','⇄','双轨视图']];
const titles={dashboard:['OVERVIEW','早上好，继续向前。'],tasks:['DAILY RHYTHM','今天要完成什么？'],searchhub:['SEARCH HUB','一次搜索，打开所有渠道'],jobs:['OPPORTUNITIES','岗位 Tracker'],network:['RELATIONSHIPS','Networking Tracker'],portfolio:['CRAFT & PROOF','Portfolio 项目'],timeline:['AUG 2026 — JUN 2027','你的求职时间线'],strategy:['TWO-TRACK STRATEGY','美国优先，中国精选']};
function load(){try{return {...structuredClone(initialData),...JSON.parse(localStorage.getItem(STORAGE_KEY))}}catch{return structuredClone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));render();}
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function init(){document.getElementById('nav').innerHTML=navItems.map(([id,icon,label])=>`<button class="nav-item" data-view="${id}"><i>${icon}</i>${label}</button>`).join('');document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());document.getElementById('nav').onclick=e=>{let b=e.target.closest('[data-view]');if(b){currentView=b.dataset.view;render()}};document.getElementById('quickAdd').onclick=()=>openModal(currentView==='dashboard'?'task':({tasks:'task',jobs:'job',network:'contact',portfolio:'project'}[currentView]||'task'));document.getElementById('updateBtn').onclick=()=>checkForUpdate(true);document.getElementById('resetDemo').title='清零并恢复计划模板';document.getElementById('resetDemo').onclick=()=>{if(confirm('确定清零所有进度？计划模板会保留，但你的打卡、KPI、投递、联系和作品集进度都会归零。')){data=structuredClone(initialData);save();toast('进度已清零，计划模板已保留')}};render();setTimeout(()=>checkForUpdate(false),2500)}
async function checkForUpdate(manual=false){if(!window.careerAtlas?.checkUpdate){if(manual)toast('当前版本不支持在线更新');return}let btn=document.getElementById('updateBtn');btn.textContent='检查中…';btn.disabled=true;let result=await window.careerAtlas.checkUpdate();btn.textContent='检查更新';btn.disabled=false;if(!result.ok){if(manual)toast('暂时无法连接更新服务器');return}if(!result.available){if(manual)toast(`已是最新版本 ${result.current}`);return}showUpdateModal(result)}
function showUpdateModal(info){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">UPDATE AVAILABLE</p><h2>发现新版本 ${esc(info.latest)}</h2></div><button class="close" type="button">×</button></div><p class="subtle">当前版本 ${esc(info.current)}。更新会保留你的任务、岗位、联系人和作品集数据。</p><div class="update-notes">${esc(info.notes||'包含功能改进与问题修复。')}</div><div class="modal-actions"><button class="secondary close" type="button">稍后</button><button class="primary" id="installUpdate" ${info.downloadUrl?'':'disabled'}>下载并重启安装</button></div></div></div>`;let root=document.getElementById('modalRoot');root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.innerHTML='');let install=root.querySelector('#installUpdate');install.onclick=async()=>{install.disabled=true;install.textContent='正在下载，请稍候…';try{await window.careerAtlas.installUpdate({downloadUrl:info.downloadUrl,assetName:info.assetName})}catch{install.disabled=false;install.textContent='重试下载';toast('更新下载失败，请稍后重试')}}}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.getElementById('pageEyebrow').textContent=titles[currentView][0];document.getElementById('pageTitle').textContent=titles[currentView][1];document.getElementById('content').innerHTML=({dashboard:dashboardView,tasks:tasksView,searchhub:searchHubView,jobs:jobsView,network:networkView,portfolio:portfolioView,timeline:timelineView,strategy:strategyView}[currentView])();bindView()}
const pct=(v,g)=>Math.min(100,Math.round((v/g)*100));
function stats(){let now=new Date(today()+'T12:00:00'),day=(now.getDay()+6)%7,monday=new Date(now);monday.setDate(now.getDate()-day);let sunday=new Date(monday);sunday.setDate(monday.getDate()+6);let start=monday.toISOString().slice(0,10),end=sunday.toISOString().slice(0,10),week=data.tasks.filter(t=>t.date>=start&&t.date<=end),done=week.filter(t=>t.done).length;return {completion:week.length?pct(done,week.length):0,apps:data.jobs.filter(j=>j.status!=='关注'&&j.status!=='准备申请').length,contacts:data.contacts.filter(c=>c.status!=='待联系').length,portfolio:Math.round(data.projects.reduce((s,p)=>s+Number(p.progress),0)/(data.projects.length||1))}}
function dashboardView(){let s=stats(),k=data.kpi,overall=Math.round([pct(k.portfolio,k.portfolioGoal),pct(k.applications,k.applicationGoal),pct(k.networking,k.networkingGoal),pct(k.skill,k.skillGoal)].reduce((a,b)=>a+b,0)/4),daily=data.tasks.filter(t=>t.date===today());if(!daily.length)daily=data.tasks.filter(t=>t.date>=today()).slice(0,5);return `<div class="grid stats">${statCard('本周完成率',s.completion+'%','✓','每日任务打卡')}${statCard('累计投递',s.apps,'↗','持续建立申请管线')}${statCard('有效联系人',s.contacts,'◎','已建立联系')}${statCard('作品集进度',s.portfolio+'%','◇','所有项目平均')}</div><div class="grid dashboard-grid"><div class="grid"><div class="card"><div class="card-head"><div><h2>本周 KPI</h2><span class="subtle">行动比焦虑更有用</span></div><button class="secondary" data-action="edit-kpi">更新数据</button></div><div class="kpi-wrap"><div class="progress-ring" style="--p:${overall}"><div class="ring-copy"><strong>${overall}%</strong><span>WEEKLY</span></div></div><div class="kpi-list">${kpiRow('Portfolio hours',k.portfolio,k.portfolioGoal,'h')}${kpiRow('Applications',k.applications,k.applicationGoal,'')}${kpiRow('Networking',k.networking,k.networkingGoal,'')}${kpiRow('Skill hours',k.skill,k.skillGoal,'h')}</div></div></div><div class="card"><div class="card-head"><div><h2>今日重点</h2><span class="subtle">完成一件，再开始下一件</span></div><button class="secondary" data-action="add-task">＋ 添加</button></div><div class="task-list">${daily.map(taskHtml).join('')||empty('今天没有预设任务')}</div></div></div><div class="grid"><div class="card"><div class="card-head"><h2>方向投入</h2><span class="subtle">建议比例</span></div><div class="mini-list">${direction('Spatial / Experiential / 3D',45,'主攻')}${direction('Architecture / Visualization',30,'留美保险')}${direction('China Game / Creative',25,'高质量退路')}</div></div><div class="card"><div class="card-head"><h2>下一个里程碑</h2><span class="tag">DEC 15</span></div><div class="milestone"><h3>求职基础设施完成</h3><p>CV · LinkedIn · Portfolio V1</p><p>1 个强 Unreal 项目 · 100 家目标公司</p></div><div class="milestone"><h3>本周提醒</h3><p>优先产出可展示的作品，而不是继续收藏教程。</p></div></div></div></div>`}
function statCard(label,val,icon,note){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${val}</div><div class="trend">${note}</div></div>`}
function kpiRow(label,v,g,u){return `<div class="kpi-row"><div class="kpi-meta"><span>${label}</span><b>${v}${u} / ${g}${u}</b></div><div class="bar"><span style="width:${pct(v,g)}%"></span></div></div>`}
function direction(label,p,n){return `<div class="direction-card"><div class="direction-head"><strong>${label}</strong><span>${p}%</span></div><div class="bar"><span style="width:${p}%"></span></div><p class="subtle">${n}</p></div>`}
function taskHtml(t){return `<div class="task ${t.done?'done':''}"><span class="check" data-action="toggle-task" data-id="${t.id}">${t.done?'✓':''}</span><div class="task-copy"><div class="task-title">${esc(t.title)}</div><div class="task-note">${esc(t.date||'')} · ${esc(t.note||'')}</div></div><span class="tag">${esc(t.category)}</span><span class="row-actions"><button data-action="edit-task" data-id="${t.id}">✎</button><button data-action="delete-task" data-id="${t.id}">×</button></span></div>`}
function visibleTasks(range='week',category='全部类别'){let start=today(),end=start;if(range==='week'){let d=new Date(start+'T12:00:00');d.setDate(d.getDate()+6);end=d.toISOString().slice(0,10)}else if(range==='all'){start='0000-00-00';end='9999-99-99'}return data.tasks.filter(t=>t.date>=start&&t.date<=end&&(category==='全部类别'||t.category===category)).sort((a,b)=>a.date.localeCompare(b.date))}
function tasksView(){let rows=visibleTasks();return `<div class="toolbar"><select id="dateFilter"><option value="today">今天</option><option value="week" selected>未来 7 天</option><option value="all">全部日期</option></select><select id="taskFilter"><option>全部类别</option>${['Portfolio','Applications','Networking','Skill','Planning'].map(x=>`<option>${x}</option>`)}</select><button class="primary" data-action="add-task">＋ 添加任务</button></div><div class="card"><div class="card-head"><div><h2>任务清单</h2><span class="subtle">工作日约 2–3 小时 · 周六 4–6 小时 · 周日复盘</span></div><span class="tag" id="taskCount">${rows.filter(t=>t.done).length} / ${rows.length} 完成</span></div><div class="task-list" id="allTasks">${rows.map(taskHtml).join('')||empty('这个日期范围还没有任务')}</div></div>`}
const columns={jobs:[['company','公司'],['role','岗位'],['place','国家 / 城市'],['direction','方向'],['status','状态'],['date','投递日期'],['contact','联系人'],['salary','薪资']],contacts:[['name','姓名'],['company','公司'],['role','职位'],['country','国家'],['channel','渠道'],['status','状态'],['lastDate','最近联系'],['next','下一步']]};
function searchHubView(){return `<div class="card search-hero"><div><span class="tag us">官方页面登录</span><h2>招聘与联系人搜索中心</h2><p class="subtle">输入一次关键词，再选择要打开的平台。搜索和登录发生在官方网页中，Career Atlas 不保存密码。</p></div><div class="search-form"><div class="field"><label>岗位 / 技能 / 公司关键词</label><input id="onlineQuery" value="Spatial Designer" placeholder="例如 Spatial Designer / Unreal / Gensler"></div><div class="field"><label>城市（LinkedIn 使用）</label><input id="onlineLocation" value="Los Angeles" placeholder="例如 Los Angeles"></div></div></div><div class="grid search-grid"><div class="card source-card"><span class="source-logo linkedin">in</span><div><h3>LinkedIn Jobs</h3><p>搜索美国岗位，并使用过去一周、经验等级等官方筛选。</p></div><button class="primary" data-action="open-search" data-platform="linkedin-jobs">搜索岗位 ↗</button></div><div class="card source-card"><span class="source-logo linkedin">in</span><div><h3>LinkedIn People</h3><p>搜索 UCLA 校友、目标公司设计师和 recruiter。</p></div><button class="primary" data-action="open-search" data-platform="linkedin-people">搜索联系人 ↗</button></div><div class="card source-card"><span class="source-logo handshake">H</span><div><h3>UCLA Handshake</h3><p>打开学生职位搜索；登录后在站内继续使用学校筛选。</p></div><button class="primary" data-action="open-search" data-platform="handshake">打开 Handshake ↗</button></div><div class="card source-card"><span class="source-logo twelve">12</span><div><h3>UCLA 12Twenty</h3><p>打开 UCLA 职业系统；登录后搜索职位、活动和校友资源。</p></div><button class="primary" data-action="open-search" data-platform="12twenty">打开 12Twenty ↗</button></div></div><div class="card capture-card"><div><h2>找到结果后快速保存</h2><p class="subtle">把官方网页留在浏览器中，回到这里用简短表单保存关键内容即可。</p></div><div><button class="secondary" data-action="add-contact">＋ 保存联系人</button> <button class="primary" data-action="add-job">＋ 保存岗位</button></div></div>`}
function openOnlineSearch(platform){let q=encodeURIComponent(document.getElementById('onlineQuery')?.value.trim()||''),loc=encodeURIComponent(document.getElementById('onlineLocation')?.value.trim()||'');let urls={'linkedin-jobs':`https://www.linkedin.com/jobs/search/?keywords=${q}&location=${loc}`,'linkedin-people':`https://www.linkedin.com/search/results/people/?keywords=${q}%20UCLA`,'handshake':`https://app.joinhandshake.com/stu/postings?query=${q}`,'12twenty':'https://ucla.12twenty.com/'};let url=urls[platform];if(window.careerAtlas)window.careerAtlas.openExternal(url).catch(()=>toast('无法打开网页，请检查默认浏览器'));else window.open(url,'_blank')}
function jobsView(){return trackerView('jobs','搜索公司或岗位…','添加岗位','job')}
function networkView(){return trackerView('contacts','搜索姓名或公司…','添加联系人','contact')}
function trackerView(type,placeholder,addLabel,entity){let rows=data[type];return `<div class="toolbar"><input id="search" placeholder="${placeholder}"><select id="trackFilter"><option value="">全部</option>${type==='jobs'?['美国','中国'].map(x=>`<option>${x}</option>`).join(''):['待联系','已联系','保持联系'].map(x=>`<option>${x}</option>`).join('')}</select><button class="secondary" data-action="export" data-type="${type}">⇩ 导出 CSV</button><button class="primary" data-action="add-${entity}">＋ ${addLabel}</button></div><div class="card table-card"><table><thead><tr>${columns[type].map(c=>`<th>${c[1]}</th>`).join('')}<th></th></tr></thead><tbody id="trackerBody">${trackerRows(type,rows)}</tbody></table></div>`}
function trackerRows(type,rows){if(!rows.length)return `<tr><td colspan="9">${empty('还没有记录')}</td></tr>`;return rows.map(r=>`<tr>${columns[type].map(([key])=>{let value=key==='place'?`${r.country} · ${r.city}`:r[key];return `<td>${key==='status'?`<span class="status ${esc(value)}">${esc(value)}</span>`:esc(value||'—')}</td>`}).join('')}<td class="row-actions"><button data-action="edit-${type==='jobs'?'job':'contact'}" data-id="${r.id}">✎</button><button data-action="delete-${type==='jobs'?'job':'contact'}" data-id="${r.id}">×</button></td></tr>`).join('')}
function portfolioView(){return `<div class="toolbar"><span class="subtle">把建筑训练转化为空间叙事、实时 3D 与视觉设计能力。</span><button class="secondary" data-action="export" data-type="projects">⇩ 导出 CSV</button><button class="primary" data-action="add-project">＋ 添加项目</button></div><div class="grid portfolio-grid">${data.projects.map(p=>`<div class="card project-card"><div class="project-top"><span class="tag ${p.track==='美国'?'us':p.track==='中国'?'cn':'both'}">${esc(p.track)}</span><span class="row-actions"><button data-action="edit-project" data-id="${p.id}">✎</button><button data-action="delete-project" data-id="${p.id}">×</button></span></div><h3>${esc(p.name)}</h3><span class="subtle">${esc(p.type)} · ${esc(p.deadline)}</span><p>下一步：${esc(p.next)}</p><div class="project-progress"><span>Progress</span><b>${p.progress}%</b></div><div class="bar"><span style="width:${p.progress}%"></span></div></div>`).join('')||empty('还没有作品集项目')}</div>`}
function timelineView(){let milestones=[['2026.08 — 09','定位与基础建设',['确定美国主攻 Spatial / Experiential / 3D，Architecture 保底','完成美国版 CV、LinkedIn 与作品集架构','建立第一批 30 家目标公司名单']],['2026.10 — 12','作品集 V1 与稳定投递',['完成 Unreal / Environment Hero Project','作品集 V1、100 家目标公司、每周稳定 networking','12 月 15 日前完成全部求职基础设施']],['2027.01 — 03','招聘旺季：扩大管线',['累计投递 150–200 个美国岗位','建立 80–120 个有效行业联系人','Portfolio V2 成熟；启动中国游戏 / 创意设计线']],['2027.04 — 05','面试、作品测试与双轨比较',['集中准备面试故事与 take-home test','跟进美国机会；参加中国春招 / 补录','比较岗位成长性、签证、薪资与城市成本']],['2027.06','毕业与 Offer 决策',['理想结果：美国 Spatial / Game / Architecture Offer 与中国游戏 / Creative Offer 可比较','确认 OPT 时间线、入职文件与搬迁安排']]];return `<div class="card timeline">${milestones.map((m,i)=>`<div class="milestone ${i===0?'active':''}"><span class="tag">${m[0]}</span><h3 style="margin-top:10px">${m[1]}</h3><ul>${m[2].map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div>`}
function strategyView(){return `<div class="grid strategy-grid"><div class="card strategy-panel us-panel"><span class="tag us">美国 · 主线 75%</span><h2>先争取 3 年 STEM 窗口</h2><p class="subtle">用 Architecture + 3D + Unreal + AI + Spatial Storytelling 的交叉优势切入。</p><ul><li><b>45%</b> Spatial / Experiential / Immersive / 3D</li><li><b>30%</b> Architecture / Visualization 留美保险</li><li>关键词：Experiential Designer、Spatial Designer、World Builder、Unreal Artist、Virtual Production</li><li>作品集先证明空间叙事，再证明实时 3D workflow</li></ul></div><div class="card strategy-panel cn-panel"><span class="tag cn">中国 · 精选 25%</span><h2>只投游戏与创意设计</h2><p class="subtle">不回到传统建筑赛道；把中国线作为高质量选择，而不是被动退路。</p><ul><li>Game Environment / 场景设计 / 世界构建</li><li>3D Creative / AI Visual Development</li><li>优先有完整培养体系、作品导向与跨界空间的团队</li><li>2027 年初集中启动，保持作品集双语版本</li></ul></div></div>`}
function empty(s){return `<div class="empty">${s}</div>`}
function bindView(){document.getElementById('content').onclick=e=>{let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action,id=b.dataset.id;if(a==='toggle-task'){let t=data.tasks.find(x=>x.id===id);t.done=!t.done;save()}else if(a==='open-search')openOnlineSearch(b.dataset.platform);else if(a.startsWith('add-'))openModal(a.slice(4));else if(a.startsWith('edit-'))openModal(a.slice(5),id);else if(a.startsWith('delete-'))remove(a.slice(7),id);else if(a==='edit-kpi')openModal('kpi');else if(a==='export')exportCsv(b.dataset.type)};let search=document.getElementById('search'),filter=document.getElementById('trackFilter');if(search){let run=()=>{let type=currentView==='jobs'?'jobs':'contacts',q=search.value.toLowerCase(),f=filter.value;let rows=data[type].filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)&&(type==='jobs'?(!f||r.country===f):(!f||r.status===f)));document.getElementById('trackerBody').innerHTML=trackerRows(type,rows)};search.oninput=run;filter.onchange=run}let tf=document.getElementById('taskFilter'),df=document.getElementById('dateFilter');if(tf&&df){let run=()=>{let rows=visibleTasks(df.value,tf.value);document.getElementById('allTasks').innerHTML=rows.map(taskHtml).join('')||empty('这个筛选范围还没有任务');document.getElementById('taskCount').textContent=`${rows.filter(t=>t.done).length} / ${rows.length} 完成`};tf.onchange=run;df.onchange=run}}
function remove(type,id){let map={task:'tasks',job:'jobs',contact:'contacts',project:'projects'},key=map[type];if(confirm('确定删除这条记录？')){data[key]=data[key].filter(x=>x.id!==id);save();toast('已删除')}}
const forms={
 task:{title:'任务',key:'tasks',fields:[['title','任务名称','text'],['category','类别','select',['Portfolio','Applications','Networking','Skill','Planning']],['date','日期','date'],['note','说明','textarea']]},
 job:{title:'岗位',key:'jobs',fields:[['company','公司','text'],['role','岗位','text'],['country','国家','select',['美国','中国']],['city','城市','text'],['direction','方向','select',['Experiential','Spatial / 3D','Game','Architecture','Visualization','AI / Creative']],['status','状态','select',['关注','准备申请','已申请','面试中','Offer','拒绝']],['date','投递日期','date'],['contact','联系人','text'],['salary','薪资','text'],['notes','备注','textarea']]},
 contact:{title:'联系人',key:'contacts',fields:[['name','姓名','text'],['company','公司','text'],['role','职位','text'],['country','国家','select',['美国','中国']],['channel','渠道','select',['LinkedIn','Email','微信','校友活动','其他']],['status','状态','select',['待联系','已联系','保持联系']],['lastDate','最近联系','date'],['next','下一步','text'],['notes','备注','textarea']]},
 project:{title:'作品集项目',key:'projects',fields:[['name','项目名称','text'],['type','类型 / 方向','text'],['track','轨道','select',['美国','中国','美国/中国']],['progress','进度 %','number'],['deadline','目标日期','date'],['next','下一步行动','text'],['notes','备注','textarea']]}
};
function openModal(type,id){if(type==='kpi')return kpiModal();let f=forms[type]||forms.task,item=id?data[f.key].find(x=>x.id===id):{};document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="editForm"><div class="modal-head"><div><p class="eyebrow">${id?'EDIT':'NEW'}</p><h2>${id?'编辑':'添加'}${f.title}</h2></div><button class="close" type="button">×</button></div><div class="form-grid">${f.fields.map(([key,label,input,opts])=>fieldHtml(key,label,input,opts,item[key])).join('')}</div><div class="modal-actions"><button class="secondary close" type="button">取消</button><button class="primary" type="submit">保存</button></div></form></div>`;wireModal(form=>{let obj={...item,id:item.id||uid()};f.fields.forEach(([key,,input])=>obj[key]=input==='number'?Number(form.elements[key].value):form.elements[key].value);if(!id&&type==='task')obj.done=false;if(id)data[f.key]=data[f.key].map(x=>x.id===id?obj:x);else data[f.key].unshift(obj);save();toast('已保存')})}
function fieldHtml(key,label,type,opts,val=''){let full=type==='textarea'?' full':'';let control=type==='select'?`<select name="${key}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${key}">${esc(val)}</textarea>`:`<input name="${key}" type="${type}" value="${esc(val)}" ${key==='progress'?'min="0" max="100"':''}>`;return `<div class="field${full}"><label>${label}</label>${control}</div>`}
function kpiModal(){let k=data.kpi;document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="editForm"><div class="modal-head"><div><p class="eyebrow">WEEKLY CHECK-IN</p><h2>更新本周 KPI</h2></div><button class="close" type="button">×</button></div><div class="form-grid">${[['portfolio','Portfolio hours'],['applications','Applications'],['networking','Networking'],['skill','Skill hours']].map(([key,l])=>fieldHtml(key,l,'number',null,k[key])).join('')}</div><div class="modal-actions"><button class="secondary close" type="button">取消</button><button class="primary">保存</button></div></form></div>`;wireModal(form=>{['portfolio','applications','networking','skill'].forEach(x=>data.kpi[x]=Number(form.elements[x].value));save();toast('本周进度已更新')})}
function wireModal(onSubmit){let root=document.getElementById('modalRoot');root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.innerHTML='');root.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))root.innerHTML=''};root.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(e.target);root.innerHTML=''}}
function exportCsv(type){let rows=data[type],cols=type==='jobs'?['company','role','country','city','direction','status','date','contact','salary','notes']:type==='contacts'?['name','company','role','country','channel','status','lastDate','next','notes']:['name','type','track','progress','deadline','next','notes'];let csv=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replace(/"/g,'""')}"`).join(','))].join('\r\n');let names={jobs:'Career-Atlas-Jobs.csv',contacts:'Career-Atlas-Networking.csv',projects:'Career-Atlas-Portfolio.csv'};if(window.careerAtlas)window.careerAtlas.exportCsv({filename:names[type],content:csv}).then(r=>!r.canceled&&toast('CSV 已导出'));else{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download=names[type];a.click();toast('CSV 已导出')}}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
